/* WordQuest — 고3·수능 대비 고급 어휘 팩(주제별 큐레이션).
   특정 출판사 교과서 목록이 아니라, 수능·모의고사에 반복 출현하는 고3 수준 고급 어휘를
   주제별로 직접 선별한 세트. 뜻은 표준 사전 의미, 예문은 원형 포함(cloze 출제 가능·자체 작성).
   형식: {w, pos, m, ex, th(주제)}. index.html 로직과 분리된 데이터. */
window.WORDPACK_HS3 = [
  // ── 논리·주장 ──
  {w:'assert',pos:'v',m:'주장하다',ex:'He asserted that the plan was safe.',th:'논리·주장'},
  {w:'imply',pos:'v',m:'암시하다',ex:'Her smile implied that she agreed.',th:'논리·주장'},
  {w:'contradict',pos:'v',m:'모순되다; 반박하다',ex:'His actions contradict his words.',th:'논리·주장'},
  {w:'justify',pos:'v',m:'정당화하다',ex:'Nothing can justify such cruelty.',th:'논리·주장'},
  {w:'plausible',pos:'a',m:'그럴듯한',ex:'That is a plausible explanation.',th:'논리·주장'},
  {w:'coherent',pos:'a',m:'일관된; 논리적인',ex:'She gave a clear, coherent answer.',th:'논리·주장'},
  {w:'ambiguous',pos:'a',m:'모호한',ex:'The rule was too ambiguous to follow.',th:'논리·주장'},
  {w:'objective',pos:'a',m:'객관적인',ex:'A judge must stay objective.',th:'논리·주장'},
  {w:'assess',pos:'v',m:'평가하다',ex:'Teachers assess students’ progress.',th:'논리·주장'},
  {w:'infer',pos:'v',m:'추론하다',ex:'We can infer the meaning from context.',th:'논리·주장'},
  // ── 변화·경향 ──
  {w:'fluctuate',pos:'v',m:'변동하다',ex:'Prices fluctuate with the season.',th:'변화·경향'},
  {w:'diminish',pos:'v',m:'줄어들다',ex:'His interest diminished over time.',th:'변화·경향'},
  {w:'enhance',pos:'v',m:'향상시키다',ex:'Music can enhance your mood.',th:'변화·경향'},
  {w:'deteriorate',pos:'v',m:'악화되다',ex:'The weather deteriorated quickly.',th:'변화·경향'},
  {w:'transform',pos:'v',m:'변형시키다',ex:'The internet transformed daily life.',th:'변화·경향'},
  {w:'prevail',pos:'v',m:'만연하다; 우세하다',ex:'Calm finally prevailed in the room.',th:'변화·경향'},
  {w:'emerge',pos:'v',m:'나타나다',ex:'New problems emerged during the trip.',th:'변화·경향'},
  {w:'restore',pos:'v',m:'회복시키다; 복원하다',ex:'They restored the old building.',th:'변화·경향'},
  {w:'undergo',pos:'v',m:'겪다',ex:'The city underwent great changes.',th:'변화·경향'},
  {w:'undermine',pos:'v',m:'약화시키다',ex:'Doubt can undermine confidence.',th:'변화·경향'},
  // ── 인식·사고 ──
  {w:'perceive',pos:'v',m:'인식하다; 지각하다',ex:'We perceive colors through the eyes.',th:'인식·사고'},
  {w:'conceive',pos:'v',m:'상상하다; 생각해내다',ex:'It is hard to conceive such a scale.',th:'인식·사고'},
  {w:'notion',pos:'n',m:'개념; 관념',ex:'He had no notion of the danger.',th:'인식·사고'},
  {w:'skeptical',pos:'a',m:'회의적인',ex:'She was skeptical about the offer.',th:'인식·사고'},
  {w:'subtle',pos:'a',m:'미묘한',ex:'There is a subtle difference between them.',th:'인식·사고'},
  {w:'profound',pos:'a',m:'심오한; 깊은',ex:'The book had a profound effect on me.',th:'인식·사고'},
  {w:'discern',pos:'v',m:'식별하다',ex:'It is hard to discern the truth here.',th:'인식·사고'},
  {w:'contemplate',pos:'v',m:'심사숙고하다',ex:'He contemplated the meaning of life.',th:'인식·사고'},
  {w:'cognitive',pos:'a',m:'인지의',ex:'Reading builds cognitive skills.',th:'인식·사고'},
  {w:'intuition',pos:'n',m:'직관',ex:'Trust your intuition sometimes.',th:'인식·사고'},
  // ── 사회·제도 ──
  {w:'legitimate',pos:'a',m:'정당한; 합법적인',ex:'They had a legitimate reason to complain.',th:'사회·제도'},
  {w:'autonomy',pos:'n',m:'자율성',ex:'Teenagers want more autonomy.',th:'사회·제도'},
  {w:'consensus',pos:'n',m:'합의',ex:'The group reached a consensus.',th:'사회·제도'},
  {w:'prohibit',pos:'v',m:'금지하다',ex:'The law prohibits smoking here.',th:'사회·제도'},
  {w:'advocate',pos:'v',m:'옹호하다',ex:'She advocates for equal rights.',th:'사회·제도'},
  {w:'regulate',pos:'v',m:'규제하다',ex:'Laws regulate how firms behave.',th:'사회·제도'},
  {w:'welfare',pos:'n',m:'복지',ex:'The state cares for public welfare.',th:'사회·제도'},
  {w:'reform',pos:'n',m:'개혁',ex:'The school needs serious reform.',th:'사회·제도'},
  {w:'oppress',pos:'v',m:'억압하다',ex:'The people were oppressed for years.',th:'사회·제도'},
  {w:'civil',pos:'a',m:'시민의; 민간의',ex:'Voting is a civil right.',th:'사회·제도'},
  // ── 학문·특성 ──
  {w:'empirical',pos:'a',m:'경험적인; 실증적인',ex:'The claim lacks empirical support.',th:'학문·특성'},
  {w:'hypothesis',pos:'n',m:'가설',ex:'The experiment tested a hypothesis.',th:'학문·특성'},
  {w:'phenomenon',pos:'n',m:'현상',ex:'Rainbows are a natural phenomenon.',th:'학문·특성'},
  {w:'inherent',pos:'a',m:'내재된; 고유의',ex:'Risk is inherent in any sport.',th:'학문·특성'},
  {w:'intrinsic',pos:'a',m:'본질적인',ex:'Curiosity has intrinsic value.',th:'학문·특성'},
  {w:'comprehensive',pos:'a',m:'포괄적인',ex:'We need a comprehensive plan.',th:'학문·특성'},
  {w:'fundamental',pos:'a',m:'근본적인',ex:'Trust is fundamental to friendship.',th:'학문·특성'},
  {w:'arbitrary',pos:'a',m:'임의의; 제멋대로인',ex:'The choice seemed completely arbitrary.',th:'학문·특성'},
  {w:'rigorous',pos:'a',m:'엄격한',ex:'The test was rigorous and fair.',th:'학문·특성'},
  {w:'feasible',pos:'a',m:'실현 가능한',ex:'Is the project feasible on time?',th:'학문·특성'},
  // ── 정도·양 ──
  {w:'abundant',pos:'a',m:'풍부한',ex:'The region has abundant water.',th:'정도·양'},
  {w:'adequate',pos:'a',m:'충분한; 적절한',ex:'We have adequate food for a week.',th:'정도·양'},
  {w:'excessive',pos:'a',m:'과도한',ex:'Excessive noise is harmful.',th:'정도·양'},
  {w:'immense',pos:'a',m:'거대한',ex:'The desert covers an immense area.',th:'정도·양'},
  {w:'minimal',pos:'a',m:'최소의',ex:'The plan needs minimal effort.',th:'정도·양'},
  {w:'moderate',pos:'a',m:'적당한; 온건한',ex:'Do moderate exercise daily.',th:'정도·양'},
  {w:'numerous',pos:'a',m:'수많은',ex:'She has numerous friends.',th:'정도·양'},
  {w:'scarce',pos:'a',m:'부족한; 드문',ex:'Clean water is scarce there.',th:'정도·양'},
  {w:'substantial',pos:'a',m:'상당한',ex:'They made a substantial profit.',th:'정도·양'},
  {w:'vast',pos:'a',m:'광대한',ex:'A vast forest covered the land.',th:'정도·양'},
  // ── 관계·영향 ──
  {w:'affect',pos:'v',m:'영향을 미치다',ex:'Weather can affect your mood.',th:'관계·영향'},
  {w:'contribute',pos:'v',m:'기여하다',ex:'Everyone contributed to the fund.',th:'관계·영향'},
  {w:'correlate',pos:'v',m:'상관관계가 있다',ex:'Sleep correlates with better grades.',th:'관계·영향'},
  {w:'derive',pos:'v',m:'끌어내다; 유래하다',ex:'The word derives from Latin.',th:'관계·영향'},
  {w:'influence',pos:'v',m:'영향을 주다',ex:'Friends influence our choices.',th:'관계·영향'},
  {w:'interact',pos:'v',m:'상호작용하다',ex:'Users interact through the app.',th:'관계·영향'},
  {w:'rely',pos:'v',m:'의존하다',ex:'We rely on the bus to school.',th:'관계·영향'},
  {w:'stem',pos:'v',m:'기인하다; 유래하다',ex:'The problem stems from poor planning.',th:'관계·영향'},
  {w:'trigger',pos:'v',m:'유발하다',ex:'The news triggered panic.',th:'관계·영향'},
  {w:'impose',pos:'v',m:'부과하다; 강요하다',ex:'They imposed new rules on us.',th:'관계·영향'},
  // ── 행동·태도 ──
  {w:'pursue',pos:'v',m:'추구하다',ex:'She pursued her goal for years.',th:'행동·태도'},
  {w:'resist',pos:'v',m:'저항하다; 참다',ex:'He could not resist the cake.',th:'행동·태도'},
  {w:'sustain',pos:'v',m:'지속시키다; 유지하다',ex:'Plants sustain life on Earth.',th:'행동·태도'},
  {w:'tolerate',pos:'v',m:'참다; 견디다',ex:'I cannot tolerate the noise.',th:'행동·태도'},
  {w:'undertake',pos:'v',m:'착수하다; 떠맡다',ex:'They undertook a huge project.',th:'행동·태도'},
  {w:'comply',pos:'v',m:'따르다; 준수하다',ex:'Please comply with the rules.',th:'행동·태도'},
  {w:'hesitate',pos:'v',m:'망설이다',ex:'Do not hesitate to ask for help.',th:'행동·태도'},
  {w:'strive',pos:'v',m:'분투하다; 애쓰다',ex:'We strive to do our best.',th:'행동·태도'},
  {w:'yield',pos:'v',m:'양보하다; 산출하다',ex:'The field yields a large crop.',th:'행동·태도'},
  {w:'cope',pos:'v',m:'대처하다',ex:'She copes well with stress.',th:'행동·태도'},
  // ── 특성·상태 ──
  {w:'crucial',pos:'a',m:'중대한',ex:'Timing is crucial in cooking.',th:'특성·상태'},
  {w:'distinct',pos:'a',m:'뚜렷한; 별개의',ex:'Each region has a distinct style.',th:'특성·상태'},
  {w:'dominant',pos:'a',m:'지배적인; 우세한',ex:'English is a dominant language.',th:'특성·상태'},
  {w:'dynamic',pos:'a',m:'역동적인',ex:'The city has a dynamic culture.',th:'특성·상태'},
  {w:'essential',pos:'a',m:'필수적인',ex:'Water is essential for life.',th:'특성·상태'},
  {w:'evident',pos:'a',m:'명백한',ex:'Her joy was evident to all.',th:'특성·상태'},
  {w:'potential',pos:'a',m:'잠재적인',ex:'He is a potential leader.',th:'특성·상태'},
  {w:'precise',pos:'a',m:'정확한',ex:'Give me the precise time.',th:'특성·상태'},
  {w:'prominent',pos:'a',m:'저명한; 두드러진',ex:'She is a prominent scientist.',th:'특성·상태'},
  {w:'complex',pos:'a',m:'복잡한',ex:'The problem is very complex.',th:'특성·상태'},
  // ── 문제·해결 ──
  {w:'obstacle',pos:'n',m:'장애물',ex:'Fear is the biggest obstacle.',th:'문제·해결'},
  {w:'dilemma',pos:'n',m:'딜레마; 진퇴양난',ex:'He faced a hard dilemma.',th:'문제·해결'},
  {w:'resolve',pos:'v',m:'해결하다; 결심하다',ex:'They resolved the conflict calmly.',th:'문제·해결'},
  {w:'overcome',pos:'v',m:'극복하다',ex:'She overcame many difficulties.',th:'문제·해결'},
  {w:'remedy',pos:'n',m:'해결책; 치료법',ex:'There is no easy remedy.',th:'문제·해결'},
  {w:'tackle',pos:'v',m:'달려들다 (문제에)',ex:'We must tackle the issue now.',th:'문제·해결'},
  {w:'address',pos:'v',m:'다루다 (문제를)',ex:'The mayor addressed the problem.',th:'문제·해결'},
  {w:'ease',pos:'v',m:'완화하다; 덜어주다',ex:'The medicine eased the pain.',th:'문제·해결'},
  {w:'alleviate',pos:'v',m:'경감하다 (고통을)',ex:'Rest can alleviate stress.',th:'문제·해결'},
  {w:'confront',pos:'v',m:'직면하다; 맞서다',ex:'We must confront the truth.',th:'문제·해결'}
];
