/* WordQuest — 철자 혼동 어휘 팩(고1·수능 빈출 혼동 어휘 20세트).
   철자가 비슷해 헷갈리는 단어쌍(access vs excess 등)을 짝으로 묶어 학습.
   형식: {w, pos, m, ex, th(혼동쌍)}. 예문은 단어 원형 포함(cloze 출제 가능)·아포스트로피 금지.
   index.html 로직과 분리된 데이터. 주제(th)는 두 단어가 같은 쌍으로 묶여 함께 시딩된다. */
window.WORDPACK_CONFUSE = [
  // ① access/excess · adapt/adopt · affect/effect · anticipate/participate
  {w:'access',pos:'n',m:'접근, 이용(권리); 접근하다',ex:'Everyone should have access to clean water.',th:'access vs excess'},
  {w:'excess',pos:'n',m:'초과, 과잉',ex:'An excess of sugar is bad for your health.',th:'access vs excess'},
  {w:'adapt',pos:'v',m:'적응하다; 각색하다',ex:'Animals adapt to their new environment.',th:'adapt vs adopt'},
  {w:'adopt',pos:'v',m:'채택하다 (방법·사상을); 입양하다',ex:'The school will adopt a new rule.',th:'adapt vs adopt'},
  {w:'affect',pos:'v',m:'영향을 미치다',ex:'Bad weather can affect our mood.',th:'affect vs effect'},
  {w:'effect',pos:'n',m:'영향; 결과; 효과',ex:'The medicine had a strong effect.',th:'affect vs effect'},
  {w:'anticipate',pos:'v',m:'기대하다, 예상하다',ex:'We anticipate a busy weekend.',th:'anticipate vs participate'},
  {w:'participate',pos:'v',m:'참여하다, 참석하다',ex:'Many students participate in the club.',th:'anticipate vs participate'},
  // ② appropriate/approximate · aptitude/attitude · astrology/astronomy · banish/vanish
  {w:'appropriate',pos:'a',m:'적절한, 적합한',ex:'Wear appropriate clothes for the interview.',th:'appropriate vs approximate'},
  {w:'approximate',pos:'a',m:'대략적인',ex:'Give me an approximate number of guests.',th:'appropriate vs approximate'},
  {w:'aptitude',pos:'n',m:'적성, 재능',ex:'She has an aptitude for math.',th:'aptitude vs attitude'},
  {w:'attitude',pos:'n',m:'태도, 자세',ex:'A positive attitude helps you grow.',th:'aptitude vs attitude'},
  {w:'astrology',pos:'n',m:'점성술',ex:'He reads about astrology every morning.',th:'astrology vs astronomy'},
  {w:'astronomy',pos:'n',m:'천문학',ex:'Astronomy is the study of the stars.',th:'astrology vs astronomy'},
  {w:'banish',pos:'v',m:'추방하다',ex:'The king decided to banish the traitor.',th:'banish vs vanish'},
  {w:'vanish',pos:'v',m:'사라지다',ex:'The stars vanish at sunrise.',th:'banish vs vanish'},
  // ③ beside/besides · blade/blaze · bleed/breed · carve/crave
  {w:'beside',pos:'prep',m:'~ 옆에',ex:'She sat down beside her friend.',th:'beside vs besides'},
  {w:'besides',pos:'ad',m:'게다가; ~ 이외에도',ex:'I am tired, and besides, it is late.',th:'beside vs besides'},
  {w:'blade',pos:'n',m:'날 (칼·도구 등의)',ex:'The blade of the knife is very sharp.',th:'blade vs blaze'},
  {w:'blaze',pos:'n',m:'불, 화재; 활활 타다',ex:'The fire grew into a huge blaze.',th:'blade vs blaze'},
  {w:'bleed',pos:'v',m:'피를 흘리다, 출혈하다',ex:'The deep cut made his hand bleed.',th:'bleed vs breed'},
  {w:'breed',pos:'v',m:'새끼를 낳다; 사육하다; 품종',ex:'They breed horses on the farm.',th:'bleed vs breed'},
  {w:'carve',pos:'v',m:'조각하다, 새기다',ex:'The artist likes to carve wood.',th:'carve vs crave'},
  {w:'crave',pos:'v',m:'갈망하다, 열망하다',ex:'Many people crave love and attention.',th:'carve vs crave'},
  // ④ cemetery/comet · choir/chore · competent/competitive · comprise/compromise
  {w:'cemetery',pos:'n',m:'묘지 (공동)',ex:'They visited the old cemetery on Sunday.',th:'cemetery vs comet'},
  {w:'comet',pos:'n',m:'혜성',ex:'A bright comet crossed the night sky.',th:'cemetery vs comet'},
  {w:'choir',pos:'n',m:'합창단, 성가대',ex:'She sings in the school choir.',th:'choir vs chore'},
  {w:'chore',pos:'n',m:'잡일, 자질구레한 일',ex:'Washing dishes is my daily chore.',th:'choir vs chore'},
  {w:'competent',pos:'a',m:'유능한, 능숙한',ex:'She is a competent and careful doctor.',th:'competent vs competitive'},
  {w:'competitive',pos:'a',m:'경쟁의, 경쟁적인; 경쟁력 있는',ex:'The job market is very competitive.',th:'competent vs competitive'},
  {w:'comprise',pos:'v',m:'구성하다, ~으로 이루어지다',ex:'The team comprise five players.',th:'comprise vs compromise'},
  {w:'compromise',pos:'n',m:'타협; 타협하다',ex:'They reached a fair compromise.',th:'comprise vs compromise'},
  // ⑤ confident/confidential · confirm/conform · conscientious/conscious · considerable/considerate
  {w:'confident',pos:'a',m:'자신 있는; 확신하는',ex:'She felt confident before the test.',th:'confident vs confidential'},
  {w:'confidential',pos:'a',m:'비밀의, 기밀의',ex:'He sent a confidential report to the boss.',th:'confident vs confidential'},
  {w:'confirm',pos:'v',m:'확인하다 (사실임을)',ex:'Please confirm the reservation for next week.',th:'confirm vs conform'},
  {w:'conform',pos:'v',m:'따르다, 순응하다',ex:'Students must conform to the school rules.',th:'confirm vs conform'},
  {w:'conscientious',pos:'a',m:'양심적인, 성실한',ex:'He is a conscientious and honest worker.',th:'conscientious vs conscious'},
  {w:'conscious',pos:'a',m:'의식하고 있는; 의식이 있는',ex:'She was conscious of the danger.',th:'conscientious vs conscious'},
  {w:'considerable',pos:'a',m:'상당한 (수량·정도가)',ex:'Habits can have a considerable effect on us.',th:'considerable vs considerate'},
  {w:'considerate',pos:'a',m:'사려 깊은, 배려하는',ex:'It was considerate of you to call.',th:'considerable vs considerate'},
  // ⑥ cosmetic/cosmic · crucial/cruel · dairy/diary · detect/detest
  {w:'cosmetic',pos:'a',m:'화장용의, 성형의; 화장품',ex:'She sells cosmetic products online.',th:'cosmetic vs cosmic'},
  {w:'cosmic',pos:'a',m:'우주의; 어마어마한',ex:'The telescope studies cosmic rays.',th:'cosmetic vs cosmic'},
  {w:'crucial',pos:'a',m:'중대한, 결정적인',ex:'Sleep plays a crucial role in health.',th:'crucial vs cruel'},
  {w:'cruel',pos:'a',m:'잔인한',ex:'It is cruel to hurt animals.',th:'crucial vs cruel'},
  {w:'dairy',pos:'n',m:'유제품의, 낙농의',ex:'Milk and cheese are dairy products.',th:'dairy vs diary'},
  {w:'diary',pos:'n',m:'일기(장)',ex:'He writes in his diary every day.',th:'dairy vs diary'},
  {w:'detect',pos:'v',m:'발견하다, 감지하다',ex:'The device can detect small leaks.',th:'detect vs detest'},
  {w:'detest',pos:'v',m:'혐오하다, 몹시 싫어하다',ex:'I detest lies and dishonest people.',th:'detect vs detest'},
  // ⑦ devote/devour · diploma/diplomat · dominate/donate · dreadful/dreary
  {w:'devote',pos:'v',m:'바치다, 헌신하다, 전념하다',ex:'They devote their time to the poor.',th:'devote vs devour'},
  {w:'devour',pos:'v',m:'게걸스럽게 먹어 치우다',ex:'The hungry dog will devour the meat.',th:'devote vs devour'},
  {w:'diploma',pos:'n',m:'졸업장; 수료증',ex:'She earned a diploma in nursing.',th:'diploma vs diplomat'},
  {w:'diplomat',pos:'n',m:'외교관',ex:'The diplomat met leaders from two countries.',th:'diploma vs diplomat'},
  {w:'dominate',pos:'v',m:'지배하다, 장악하다',ex:'One team began to dominate the game.',th:'dominate vs donate'},
  {w:'donate',pos:'v',m:'기부하다, 기증하다',ex:'They donate money to the orphanage.',th:'dominate vs donate'},
  {w:'dreadful',pos:'a',m:'끔찍한, 지독한',ex:'It was a cold and dreadful night.',th:'dreadful vs dreary'},
  {w:'dreary',pos:'a',m:'음울한, 적막한',ex:'The winter sky looked gray and dreary.',th:'dreadful vs dreary'},
  // ⑧ economic/economical · election/erection · emit/omit · ethic/ethnic
  {w:'economic',pos:'a',m:'경제의',ex:'These factors caused economic differences.',th:'economic vs economical'},
  {w:'economical',pos:'a',m:'경제적인, 절약하는',ex:'The small car is very economical on fuel.',th:'economic vs economical'},
  {w:'election',pos:'n',m:'선거, 투표',ex:'The election will be held next month.',th:'election vs erection'},
  {w:'erection',pos:'n',m:'건립, 건설',ex:'He supervised the erection of a new building.',th:'election vs erection'},
  {w:'emit',pos:'v',m:'방출하다, 내뿜다',ex:'Cars emit gases that pollute the air.',th:'emit vs omit'},
  {w:'omit',pos:'v',m:'빠뜨리다, 생략하다',ex:'Do not omit any important detail.',th:'emit vs omit'},
  {w:'ethic',pos:'n',m:'윤리, 도덕',ex:'Every worker should know the work ethic.',th:'ethic vs ethnic'},
  {w:'ethnic',pos:'a',m:'민족의, 인종의',ex:'America is known for its ethnic diversity.',th:'ethic vs ethnic'},
  // ⑨ fame/famine · favor/flavor · feather/leather · fertile/futile
  {w:'fame',pos:'n',m:'명성',ex:'The young director cares little for fame.',th:'fame vs famine'},
  {w:'famine',pos:'n',m:'기근, 굶주림',ex:'The long drought caused a terrible famine.',th:'fame vs famine'},
  {w:'favor',pos:'n',m:'친절한 행위; 호의; 찬성',ex:'Would you do me a favor please.',th:'favor vs flavor'},
  {w:'flavor',pos:'n',m:'맛, 풍미',ex:'My favorite flavor is vanilla.',th:'favor vs flavor'},
  {w:'feather',pos:'n',m:'깃털',ex:'A bald eagle has a white feather on its head.',th:'feather vs leather'},
  {w:'leather',pos:'n',m:'가죽',ex:'The men were wearing leather jackets.',th:'feather vs leather'},
  {w:'fertile',pos:'a',m:'비옥한',ex:'The fertile soil is good for farming.',th:'fertile vs futile'},
  {w:'futile',pos:'a',m:'헛된, 소용없는',ex:'It was a futile attempt to fix the computer.',th:'fertile vs futile'},
  // ⑩ flash/flush · flesh/fresh · fraction/friction · furnish/punish
  {w:'flash',pos:'v',m:'번쩍이다, 빛나다; 섬광',ex:'The camera flash was too bright.',th:'flash vs flush'},
  {w:'flush',pos:'v',m:'물을 내리다 (변기의); 붉어지다',ex:'Do not forget to flush the toilet.',th:'flash vs flush'},
  {w:'flesh',pos:'n',m:'살, 육체',ex:'A robot needs language and flesh to feel human.',th:'flesh vs fresh'},
  {w:'fresh',pos:'a',m:'신선한, 새로운',ex:'We bought fresh fruit at the market.',th:'flesh vs fresh'},
  {w:'fraction',pos:'n',m:'일부, 부분',ex:'Only a fraction of the people voted.',th:'fraction vs friction'},
  {w:'friction',pos:'n',m:'마찰',ex:'Oil reduces friction between the parts.',th:'fraction vs friction'},
  {w:'furnish',pos:'v',m:'비치하다 (가구를); 제공하다',ex:'Could you furnish the room with a new sofa.',th:'furnish vs punish'},
  {w:'punish',pos:'v',m:'벌을 주다, 처벌하다',ex:'Teachers should not punish students harshly.',th:'furnish vs punish'},
  // ⑪ geography/geology · infect/inject · irrigate/irritate · leap/reap
  {w:'geography',pos:'n',m:'지리학; 지형',ex:'We study the geography of the deserts.',th:'geography vs geology'},
  {w:'geology',pos:'n',m:'지질학',ex:'In geology class we studied the rocks.',th:'geography vs geology'},
  {w:'infect',pos:'v',m:'감염시키다, 전염시키다',ex:'A single cough can infect many people.',th:'infect vs inject'},
  {w:'inject',pos:'v',m:'주사하다; 주입하다',ex:'He has to inject himself with insulin.',th:'infect vs inject'},
  {w:'irrigate',pos:'v',m:'물을 대다 (땅에), 관개하다',ex:'Farmers irrigate the dry fields.',th:'irrigate vs irritate'},
  {w:'irritate',pos:'v',m:'짜증나게 하다, 화나게 하다',ex:'Loud noises irritate me when I study.',th:'irrigate vs irritate'},
  {w:'leap',pos:'v',m:'뛰어오르다, 도약하다; 도약',ex:'The cat can leap over the fence.',th:'leap vs reap'},
  {w:'reap',pos:'v',m:'수확하다, 거두다',ex:'The man will reap the rewards of hard work.',th:'leap vs reap'},
  // ⑫ liberal/literal · marital/martial · moan/mourn · momentary/momentous
  {w:'liberal',pos:'a',m:'진보적인, 자유주의의',ex:'My parents hold liberal views.',th:'liberal vs literal'},
  {w:'literal',pos:'a',m:'문자 그대로의',ex:'Give me the literal meaning of the word.',th:'liberal vs literal'},
  {w:'marital',pos:'a',m:'결혼(생활)의, 부부의',ex:'They discussed their marital problems.',th:'marital vs martial'},
  {w:'martial',pos:'a',m:'싸움의, 무술의',ex:'The women mastered martial arts for self defense.',th:'marital vs martial'},
  {w:'moan',pos:'v',m:'신음하다; 투덜거리다',ex:'The sick man began to moan in pain.',th:'moan vs mourn'},
  {w:'mourn',pos:'v',m:'슬퍼하다, 애도하다',ex:'People around the world mourn the loss.',th:'moan vs mourn'},
  {w:'momentary',pos:'a',m:'순간적인, 찰나의',ex:'There was a momentary pause in the movie.',th:'momentary vs momentous'},
  {w:'momentous',pos:'a',m:'중대한, 중요한',ex:'It was a momentous day in history.',th:'momentary vs momentous'},
  // ⑬ overlook/oversee · patrol/patron · perspective/prospective · politic/political
  {w:'overlook',pos:'v',m:'간과하다; 내려다보다',ex:'The man liked to overlook the wide sea.',th:'overlook vs oversee'},
  {w:'oversee',pos:'v',m:'감독하다, 감시하다',ex:'A good manager should oversee the work.',th:'overlook vs oversee'},
  {w:'patrol',pos:'n',m:'순찰(대); 순찰하다',ex:'The police patrol increased in the forest.',th:'patrol vs patron'},
  {w:'patron',pos:'n',m:'후원자; 단골 고객',ex:'The wealthy man was the patron of musicians.',th:'patrol vs patron'},
  {w:'perspective',pos:'n',m:'관점, 시각; 원근법',ex:'They had the same perspective on politics.',th:'perspective vs prospective'},
  {w:'prospective',pos:'a',m:'장래의, 유망한',ex:'The company met a prospective client.',th:'perspective vs prospective'},
  {w:'politic',pos:'a',m:'현명한, 신중한',ex:'It would be politic to avoid the topic.',th:'politic vs political'},
  {w:'political',pos:'a',m:'정치의; 정당의',ex:'Birth rate has become a political issue.',th:'politic vs political'},
  // ⑭ precious/previous · principal/principle · property/prosperity · prophecy/prophesy
  {w:'precious',pos:'a',m:'귀중한, 소중한',ex:'We must understand the value of precious plants.',th:'precious vs previous'},
  {w:'previous',pos:'a',m:'이전의, 앞선',ex:'He learned from his previous mistakes.',th:'precious vs previous'},
  {w:'principal',pos:'a',m:'주요한; 교장',ex:'Water is the principal cause of the flood.',th:'principal vs principle'},
  {w:'principle',pos:'n',m:'원리, 원칙',ex:'Trust is a basic principle of friendship.',th:'principal vs principle'},
  {w:'property',pos:'n',m:'재산; 특성, 속성',ex:'They think of the art as personal property.',th:'property vs prosperity'},
  {w:'prosperity',pos:'n',m:'번영, 번창',ex:'Hard work brought the town great prosperity.',th:'property vs prosperity'},
  {w:'prophecy',pos:'n',m:'예언',ex:'The old prophecy came true at last.',th:'prophecy vs prophesy'},
  {w:'prophesy',pos:'v',m:'예언하다',ex:'No one can prophesy what will happen next.',th:'prophecy vs prophesy'},
  // ⑮ protect/protest · ragged/rugged · receipt/recipe · region/religion
  {w:'protect',pos:'v',m:'보호하다',ex:'We should try to protect our environment.',th:'protect vs protest'},
  {w:'protest',pos:'v',m:'항의하다; 항의, 시위',ex:'The crowd began to protest the new law.',th:'protect vs protest'},
  {w:'ragged',pos:'a',m:'누더기의; 덥수룩한',ex:'The poor man wore ragged old clothes.',th:'ragged vs rugged'},
  {w:'rugged',pos:'a',m:'울퉁불퉁한, 험한',ex:'The climbers avoided the rugged mountains.',th:'ragged vs rugged'},
  {w:'receipt',pos:'n',m:'영수증',ex:'Keep the receipt in case you return it.',th:'receipt vs recipe'},
  {w:'recipe',pos:'n',m:'조리법',ex:'The recipe says we need flour and butter.',th:'receipt vs recipe'},
  {w:'region',pos:'n',m:'지역, 지방',ex:'Each region has its own weather.',th:'region vs religion'},
  {w:'religion',pos:'n',m:'종교',ex:'They respect every religion in the country.',th:'region vs religion'},
  // ⑯ reside/resign · resolve/revolve · respectable/respective · responsible/responsive
  {w:'reside',pos:'v',m:'거주하다, 살다',ex:'Those who reside here can get a library card.',th:'reside vs resign'},
  {w:'resign',pos:'v',m:'사직하다, 물러나다',ex:'The reporter decided to resign after the scandal.',th:'reside vs resign'},
  {w:'resolve',pos:'v',m:'해결하다; 결심하다',ex:'AI could help us resolve moral dilemmas.',th:'resolve vs revolve'},
  {w:'revolve',pos:'v',m:'회전하다, 돌다',ex:'The planets revolve around the sun.',th:'resolve vs revolve'},
  {w:'respectable',pos:'a',m:'존경할 만한, 훌륭한',ex:'I think Tony will become a respectable adult.',th:'respectable vs respective'},
  {w:'respective',pos:'a',m:'각각의, 각자의',ex:'The players went back to their respective teams.',th:'respectable vs respective'},
  {w:'responsible',pos:'a',m:'책임이 있는; 원인이 되는',ex:'The system is responsible for the weather changes.',th:'responsible vs responsive'},
  {w:'responsive',pos:'a',m:'즉각 반응하는',ex:'The car is responsive to the driver.',th:'responsible vs responsive'},
  // ⑰ rob/rub · sacred/scared · sensible/sensitive · sermon/summon
  {w:'rob',pos:'v',m:'약탈하다, 빼앗다',ex:'The thief tried to rob the travelers.',th:'rob vs rub'},
  {w:'rub',pos:'v',m:'문지르다, 비비다',ex:'She began to rub her tired eyes.',th:'rob vs rub'},
  {w:'sacred',pos:'a',m:'신성한, 성스러운',ex:'Churches are sacred to many worshipers.',th:'sacred vs scared'},
  {w:'scared',pos:'a',m:'무서워하는, 겁먹은',ex:'I was so scared that I could not shout.',th:'sacred vs scared'},
  {w:'sensible',pos:'a',m:'현명한, 분별 있는',ex:'The old man gave some sensible advice.',th:'sensible vs sensitive'},
  {w:'sensitive',pos:'a',m:'민감한, 예민한',ex:'She is so sensitive that she gets hurt easily.',th:'sensible vs sensitive'},
  {w:'sermon',pos:'n',m:'설교',ex:'The priest gave a long sermon.',th:'sermon vs summon'},
  {w:'summon',pos:'v',m:'소환하다, 호출하다',ex:'The court can summon additional witnesses.',th:'sermon vs summon'},
  // ⑱ simulate/stimulate · sparkle/sprinkle · species/specimen · staff/stuff
  {w:'simulate',pos:'v',m:'모의실험을 하다; ~인 척하다',ex:'The scientists developed a way to simulate driving.',th:'simulate vs stimulate'},
  {w:'stimulate',pos:'v',m:'자극하다, 촉진하다',ex:'A debate can stimulate students to study more.',th:'simulate vs stimulate'},
  {w:'sparkle',pos:'v',m:'반짝이다; 반짝임',ex:'The clean glasses sparkle in the light.',th:'sparkle vs sprinkle'},
  {w:'sprinkle',pos:'v',m:'뿌리다',ex:'She likes to sprinkle sugar on the bread.',th:'sparkle vs sprinkle'},
  {w:'species',pos:'n',m:'종(種), 종류',ex:'The forest is home to many rare species.',th:'species vs specimen'},
  {w:'specimen',pos:'n',m:'표본, 견본',ex:'The scientist needed a specimen for the study.',th:'species vs specimen'},
  {w:'staff',pos:'n',m:'직원',ex:'The restaurant has a staff of forty.',th:'staff vs stuff'},
  {w:'stuff',pos:'n',m:'물건; 물질; 채워 넣다',ex:'Put all your stuff in the box.',th:'staff vs stuff'},
  // ⑲ statue/status · subside/subsidy · successful/successive · text/textile
  {w:'statue',pos:'n',m:'조각상',ex:'It is hard to move the huge stone statue.',th:'statue vs status'},
  {w:'status',pos:'n',m:'지위; 상태',ex:'His social status changed after the win.',th:'statue vs status'},
  {w:'subside',pos:'v',m:'진정되다, 가라앉다',ex:'The wounded hunter waited for the pain to subside.',th:'subside vs subsidy'},
  {w:'subsidy',pos:'n',m:'보조금',ex:'The government provides a subsidy for buses.',th:'subside vs subsidy'},
  {w:'successful',pos:'a',m:'성공한, 성공적인',ex:'The show was a very successful event.',th:'successful vs successive'},
  {w:'successive',pos:'a',m:'연속적인, 연이은',ex:'It snowed for three successive days.',th:'successful vs successive'},
  {w:'text',pos:'n',m:'글, 문서',ex:'His text is too difficult to understand.',th:'text vs textile'},
  {w:'textile',pos:'n',m:'직물, 섬유',ex:'This textile is waterproof and strong.',th:'text vs textile'},
  // ⑳ thread/threat · vague/vogue · wander/wonder · weary/weird
  {w:'thread',pos:'n',m:'실, 가닥',ex:'A thread was hanging on her shoulder.',th:'thread vs threat'},
  {w:'threat',pos:'n',m:'위협, 협박',ex:'The storm is a serious threat to the town.',th:'thread vs threat'},
  {w:'vague',pos:'a',m:'모호한, 막연한',ex:'His answer was too vague to understand.',th:'vague vs vogue'},
  {w:'vogue',pos:'n',m:'유행',ex:'Short jeans were once in vogue.',th:'vague vs vogue'},
  {w:'wander',pos:'v',m:'돌아다니다, 헤매다',ex:'He saw many people wander the streets at night.',th:'wander vs wonder'},
  {w:'wonder',pos:'v',m:'궁금해하다; 놀라움',ex:'I often wonder where she went.',th:'wander vs wonder'},
  {w:'weary',pos:'a',m:'지친, 싫증이 난',ex:'She was weary of fighting with her sister.',th:'weary vs weird'},
  {w:'weird',pos:'a',m:'이상한, 기묘한',ex:'They heard a weird noise in the dark.',th:'weary vs weird'},
];
