/* WordQuest — 고2 내신·모의고사 필수 어휘 팩(주제별 큐레이션).
   특정 출판사 교과서 목록이 아니라, 여러 교과서·모의고사에 반복 출현하는 고2 수준 핵심 어휘를
   주제별로 직접 선별한 세트. 뜻은 표준 사전 의미, 예문은 원형 포함(cloze 출제 가능·자체 작성).
   형식: {w, pos, m, ex, th(주제)}. index.html 로직과 분리된 데이터. */
window.WORDPACK_HS2 = [
  // ── 학문·사고 ──
  {w:'analyze',pos:'v',m:'분석하다',ex:'Scientists analyze data to find patterns.',th:'학문·사고'},
  {w:'define',pos:'v',m:'정의하다',ex:'Please define the word in your own way.',th:'학문·사고'},
  {w:'concept',pos:'n',m:'개념',ex:'The concept was hard to understand at first.',th:'학문·사고'},
  {w:'evidence',pos:'n',m:'증거',ex:'There is strong evidence for this idea.',th:'학문·사고'},
  {w:'factor',pos:'n',m:'요인',ex:'Price is an important factor in the choice.',th:'학문·사고'},
  {w:'method',pos:'n',m:'방법',ex:'We tried a new method to solve it.',th:'학문·사고'},
  {w:'process',pos:'n',m:'과정',ex:'Learning a language is a slow process.',th:'학문·사고'},
  {w:'theory',pos:'n',m:'이론',ex:'The theory explains how birds fly.',th:'학문·사고'},
  {w:'conclude',pos:'v',m:'결론짓다',ex:'We concluded that the plan would work.',th:'학문·사고'},
  {w:'observe',pos:'v',m:'관찰하다',ex:'The students observed the insects closely.',th:'학문·사고'},
  // ── 사회·관계 ──
  {w:'community',pos:'n',m:'공동체; 지역사회',ex:'Our community helps each other.',th:'사회·관계'},
  {w:'generation',pos:'n',m:'세대',ex:'Each generation faces new challenges.',th:'사회·관계'},
  {w:'individual',pos:'n',m:'개인',ex:'Each individual has different needs.',th:'사회·관계'},
  {w:'participate',pos:'v',m:'참여하다',ex:'Everyone can participate in the event.',th:'사회·관계'},
  {w:'tradition',pos:'n',m:'전통',ex:'The festival is an old tradition.',th:'사회·관계'},
  {w:'culture',pos:'n',m:'문화',ex:'Food is a big part of any culture.',th:'사회·관계'},
  {w:'cooperate',pos:'v',m:'협력하다',ex:'The teams cooperated to finish faster.',th:'사회·관계'},
  {w:'relationship',pos:'n',m:'관계',ex:'A good relationship needs trust.',th:'사회·관계'},
  {w:'society',pos:'n',m:'사회',ex:'Technology has changed our society.',th:'사회·관계'},
  {w:'respect',pos:'v',m:'존중하다',ex:'We should respect other opinions.',th:'사회·관계'},
  // ── 자연·환경 ──
  {w:'environment',pos:'n',m:'환경',ex:'We must protect the environment.',th:'자연·환경'},
  {w:'resource',pos:'n',m:'자원',ex:'Water is a precious resource.',th:'자연·환경'},
  {w:'survive',pos:'v',m:'살아남다',ex:'Few plants survive in the desert.',th:'자연·환경'},
  {w:'climate',pos:'n',m:'기후',ex:'The climate is getting warmer.',th:'자연·환경'},
  {w:'pollution',pos:'n',m:'오염',ex:'Air pollution harms our health.',th:'자연·환경'},
  {w:'species',pos:'n',m:'(생물) 종',ex:'Many species are in danger.',th:'자연·환경'},
  {w:'protect',pos:'v',m:'보호하다',ex:'National parks protect wild animals.',th:'자연·환경'},
  {w:'energy',pos:'n',m:'에너지',ex:'Solar energy is clean and cheap.',th:'자연·환경'},
  {w:'waste',pos:'v',m:'낭비하다',ex:'Do not waste water when brushing.',th:'자연·환경'},
  {w:'natural',pos:'a',m:'자연의; 자연스러운',ex:'The park is full of natural beauty.',th:'자연·환경'},
  // ── 경제·생활 ──
  {w:'economy',pos:'n',m:'경제',ex:'The economy grew last year.',th:'경제·생활'},
  {w:'industry',pos:'n',m:'산업',ex:'The car industry employs many people.',th:'경제·생활'},
  {w:'benefit',pos:'n',m:'이익; 혜택',ex:'Exercise has many benefits.',th:'경제·생활'},
  {w:'product',pos:'n',m:'제품',ex:'The new product sold quickly.',th:'경제·생활'},
  {w:'income',pos:'n',m:'수입; 소득',ex:'He saved part of his income.',th:'경제·생활'},
  {w:'consume',pos:'v',m:'소비하다',ex:'Big cities consume a lot of energy.',th:'경제·생활'},
  {w:'demand',pos:'n',m:'수요; 요구',ex:'Demand for phones keeps rising.',th:'경제·생활'},
  {w:'supply',pos:'n',m:'공급',ex:'The store keeps a fresh supply of bread.',th:'경제·생활'},
  {w:'trade',pos:'n',m:'무역; 거래',ex:'The two countries trade with each other.',th:'경제·생활'},
  {w:'budget',pos:'n',m:'예산',ex:'We planned a budget for the trip.',th:'경제·생활'},
  // ── 성격·태도 ──
  {w:'appropriate',pos:'a',m:'적절한',ex:'Wear appropriate clothes for the weather.',th:'성격·태도'},
  {w:'aware',pos:'a',m:'알고 있는; 인식하는',ex:'Be aware of the risks before you start.',th:'성격·태도'},
  {w:'constant',pos:'a',m:'끊임없는; 일정한',ex:'She made constant efforts to improve.',th:'성격·태도'},
  {w:'effective',pos:'a',m:'효과적인',ex:'This is an effective way to study.',th:'성격·태도'},
  {w:'efficient',pos:'a',m:'효율적인',ex:'The new engine is very efficient.',th:'성격·태도'},
  {w:'moral',pos:'a',m:'도덕적인',ex:'It was a difficult moral choice.',th:'성격·태도'},
  {w:'reasonable',pos:'a',m:'합리적인; 적당한',ex:'The price seems reasonable.',th:'성격·태도'},
  {w:'relevant',pos:'a',m:'관련 있는',ex:'Keep your answer relevant to the question.',th:'성격·태도'},
  {w:'responsible',pos:'a',m:'책임이 있는',ex:'Drivers are responsible for safety.',th:'성격·태도'},
  {w:'sincere',pos:'a',m:'진심의; 진실한',ex:'She gave a sincere apology.',th:'성격·태도'},
  // ── 의사소통·언어 ──
  {w:'communicate',pos:'v',m:'의사소통하다',ex:'We communicate mostly by text.',th:'의사소통·언어'},
  {w:'express',pos:'v',m:'표현하다',ex:'Art lets people express feelings.',th:'의사소통·언어'},
  {w:'describe',pos:'v',m:'묘사하다',ex:'Can you describe what you saw?',th:'의사소통·언어'},
  {w:'argue',pos:'v',m:'논쟁하다; 주장하다',ex:'They argued about the rules.',th:'의사소통·언어'},
  {w:'persuade',pos:'v',m:'설득하다',ex:'She persuaded him to join the club.',th:'의사소통·언어'},
  {w:'translate',pos:'v',m:'번역하다',ex:'He translated the letter into Korean.',th:'의사소통·언어'},
  {w:'indicate',pos:'v',m:'나타내다; 가리키다',ex:'The sign indicates the exit.',th:'의사소통·언어'},
  {w:'mention',pos:'v',m:'언급하다',ex:'She mentioned your name today.',th:'의사소통·언어'},
  {w:'respond',pos:'v',m:'응답하다; 반응하다',ex:'Please respond to the email soon.',th:'의사소통·언어'},
  {w:'discuss',pos:'v',m:'논의하다',ex:'We discussed the plan for hours.',th:'의사소통·언어'},
  // ── 시간·빈도 ──
  {w:'gradual',pos:'a',m:'점진적인',ex:'There was a gradual change in weather.',th:'시간·빈도'},
  {w:'immediate',pos:'a',m:'즉각적인',ex:'We need an immediate answer.',th:'시간·빈도'},
  {w:'previous',pos:'a',m:'이전의',ex:'See the previous page for details.',th:'시간·빈도'},
  {w:'recent',pos:'a',m:'최근의',ex:'A recent study shows good results.',th:'시간·빈도'},
  {w:'temporary',pos:'a',m:'일시적인',ex:'This is only a temporary fix.',th:'시간·빈도'},
  {w:'frequent',pos:'a',m:'잦은',ex:'He is a frequent visitor here.',th:'시간·빈도'},
  {w:'rapid',pos:'a',m:'빠른',ex:'The city saw rapid growth.',th:'시간·빈도'},
  {w:'permanent',pos:'a',m:'영구적인',ex:'The change looks permanent now.',th:'시간·빈도'},
  {w:'delay',pos:'n',m:'지연',ex:'The delay lasted two hours.',th:'시간·빈도'},
  {w:'period',pos:'n',m:'기간; 시기',ex:'She lived here for a short period.',th:'시간·빈도'},
  // ── 건강·신체 ──
  {w:'disease',pos:'n',m:'질병',ex:'The disease spread quickly.',th:'건강·신체'},
  {w:'cure',pos:'v',m:'치료하다',ex:'This medicine can cure the illness.',th:'건강·신체'},
  {w:'medicine',pos:'n',m:'약; 의학',ex:'Take the medicine after meals.',th:'건강·신체'},
  {w:'mental',pos:'a',m:'정신의',ex:'Sleep is good for mental health.',th:'건강·신체'},
  {w:'physical',pos:'a',m:'신체의; 물리적인',ex:'Physical exercise makes you strong.',th:'건강·신체'},
  {w:'nutrition',pos:'n',m:'영양',ex:'Fruit gives good nutrition.',th:'건강·신체'},
  {w:'recover',pos:'v',m:'회복하다',ex:'He recovered from the cold.',th:'건강·신체'},
  {w:'prevent',pos:'v',m:'예방하다; 막다',ex:'Washing hands prevents disease.',th:'건강·신체'},
  {w:'symptom',pos:'n',m:'증상',ex:'A cough is a common symptom.',th:'건강·신체'},
  {w:'injury',pos:'n',m:'부상',ex:'He rested to heal his injury.',th:'건강·신체'},
  // ── 성취·도전 ──
  {w:'achieve',pos:'v',m:'성취하다',ex:'She achieved her lifelong dream.',th:'성취·도전'},
  {w:'effort',pos:'n',m:'노력',ex:'Success takes real effort.',th:'성취·도전'},
  {w:'goal',pos:'n',m:'목표',ex:'Set a clear goal for the year.',th:'성취·도전'},
  {w:'improve',pos:'v',m:'개선하다; 향상시키다',ex:'Practice will improve your skills.',th:'성취·도전'},
  {w:'knowledge',pos:'n',m:'지식',ex:'Books are a source of knowledge.',th:'성취·도전'},
  {w:'progress',pos:'n',m:'진전; 발전',ex:'We made good progress today.',th:'성취·도전'},
  {w:'succeed',pos:'v',m:'성공하다',ex:'Hard work helps you succeed.',th:'성취·도전'},
  {w:'talent',pos:'n',m:'재능',ex:'She has a talent for music.',th:'성취·도전'},
  {w:'challenge',pos:'n',m:'도전; 난관',ex:'The climb was a big challenge.',th:'성취·도전'},
  {w:'motivate',pos:'v',m:'동기를 부여하다',ex:'Good coaches motivate their players.',th:'성취·도전'},
  // ── 판단·선택 ──
  {w:'consider',pos:'v',m:'고려하다',ex:'Consider all options first.',th:'판단·선택'},
  {w:'decide',pos:'v',m:'결정하다',ex:'They decided to leave early.',th:'판단·선택'},
  {w:'determine',pos:'v',m:'결정하다; 알아내다',ex:'Tests determine your level.',th:'판단·선택'},
  {w:'doubt',pos:'n',m:'의심',ex:'I have no doubt about it.',th:'판단·선택'},
  {w:'prefer',pos:'v',m:'선호하다',ex:'I prefer tea to coffee.',th:'판단·선택'},
  {w:'refuse',pos:'v',m:'거절하다',ex:'He refused the offer politely.',th:'판단·선택'},
  {w:'select',pos:'v',m:'선택하다',ex:'Select the best answer.',th:'판단·선택'},
  {w:'suggest',pos:'v',m:'제안하다',ex:'She suggested a new idea.',th:'판단·선택'},
  {w:'tend',pos:'v',m:'~하는 경향이 있다',ex:'People tend to forget names.',th:'판단·선택'},
  {w:'ignore',pos:'v',m:'무시하다',ex:'Do not ignore the warning.',th:'판단·선택'}
];
