/* WordQuest — 고1 공통영어·수능 기초 필수 어휘 팩(주제별 큐레이션).
   특정 출판사 교과서 목록이 아니라, 여러 교과서·수능에 반복 출현하는 핵심 어휘를 주제별로 선별한 세트.
   형식: {w, pos, m, ex, th(주제)}. 예문은 원형 포함(cloze 출제 가능). index.html 로직과 분리된 데이터. */
window.WORDPACK_HS1 = [
  {w:'confident',pos:'a',m:'자신 있는',ex:'She felt confident before the big test.',th:'자아·감정'},
  {w:'anxious',pos:'a',m:'불안한',ex:'He was anxious about the exam results.',th:'자아·감정'},
  {w:'grateful',pos:'a',m:'감사하는',ex:'I am grateful for your kind help.',th:'자아·감정'},
  {w:'curious',pos:'a',m:'호기심 있는',ex:'Children are curious about everything around them.',th:'자아·감정'},
  {w:'jealous',pos:'a',m:'질투하는',ex:'He felt jealous when she won the prize.',th:'자아·감정'},
  {w:'shy',pos:'a',m:'수줍은',ex:'The shy boy rarely speaks in class.',th:'자아·감정'},
  {w:'proud',pos:'a',m:'자랑스러운',ex:'They were proud of their small team.',th:'자아·감정'},
  {w:'emotion',pos:'n',m:'감정',ex:'She could not hide her emotion.',th:'자아·감정'},
  {w:'mood',pos:'n',m:'기분',ex:'Good music can change your mood.',th:'자아·감정'},
  {w:'patience',pos:'n',m:'인내심',ex:'Learning a language takes patience.',th:'자아·감정'},
  {w:'confidence',pos:'n',m:'자신감',ex:'Daily practice builds your confidence.',th:'자아·감정'},
  {w:'desire',pos:'n',m:'욕구; 열망',ex:'She has a strong desire to succeed.',th:'자아·감정'},
  {w:'attitude',pos:'n',m:'태도',ex:'A positive attitude helps you grow.',th:'자아·감정'},
  {w:'encourage',pos:'v',m:'격려하다',ex:'Good teachers encourage students to try.',th:'자아·감정'},
  {w:'express',pos:'v',m:'표현하다',ex:'Art lets people express their feelings.',th:'자아·감정'},
  {w:'fear',pos:'n',m:'두려움',ex:'He faced his fear and went on stage.',th:'자아·감정'},
  {w:'achievement',pos:'n',m:'성취; 업적',ex:'Winning the contest was a great achievement.',th:'학교·진로'},
  {w:'effort',pos:'n',m:'노력',ex:'Success comes with steady effort.',th:'학교·진로'},
  {w:'goal',pos:'n',m:'목표',ex:'Set a clear goal for this year.',th:'학교·진로'},
  {w:'career',pos:'n',m:'진로; 경력',ex:'She wants a career in science.',th:'학교·진로'},
  {w:'knowledge',pos:'n',m:'지식',ex:'Reading builds your knowledge.',th:'학교·진로'},
  {w:'skill',pos:'n',m:'기술; 능력',ex:'Writing is an important skill.',th:'학교·진로'},
  {w:'improve',pos:'v',m:'향상시키다',ex:'Practice will improve your English.',th:'학교·진로'},
  {w:'concentrate',pos:'v',m:'집중하다',ex:'Please concentrate on your work.',th:'학교·진로'},
  {w:'graduate',pos:'v',m:'졸업하다',ex:'They will graduate next spring.',th:'학교·진로'},
  {w:'prepare',pos:'v',m:'준비하다',ex:'We should prepare for the exam early.',th:'학교·진로'},
  {w:'challenge',pos:'n',m:'도전',ex:'The new job is a real challenge.',th:'학교·진로'},
  {w:'talent',pos:'n',m:'재능',ex:'She has a talent for music.',th:'학교·진로'},
  {w:'major',pos:'n',m:'전공',ex:'History is her major at college.',th:'학교·진로'},
  {w:'progress',pos:'n',m:'진전; 발전',ex:'You can make good progress with practice.',th:'학교·진로'},
  {w:'motivate',pos:'v',m:'동기를 부여하다',ex:'A clear goal can motivate you.',th:'학교·진로'},
  {w:'succeed',pos:'v',m:'성공하다',ex:'You will succeed if you keep trying.',th:'학교·진로'},
  {w:'environment',pos:'n',m:'환경',ex:'We must protect the environment.',th:'환경·기후'},
  {w:'pollution',pos:'n',m:'오염',ex:'Air pollution is a serious problem.',th:'환경·기후'},
  {w:'climate',pos:'n',m:'기후',ex:'Climate change affects the whole planet.',th:'환경·기후'},
  {w:'resource',pos:'n',m:'자원',ex:'Water is a precious resource.',th:'환경·기후'},
  {w:'protect',pos:'v',m:'보호하다',ex:'We should protect endangered animals.',th:'환경·기후'},
  {w:'reduce',pos:'v',m:'줄이다',ex:'Please reduce your plastic use.',th:'환경·기후'},
  {w:'recycle',pos:'v',m:'재활용하다',ex:'We recycle paper and cans at home.',th:'환경·기후'},
  {w:'pollute',pos:'v',m:'오염시키다',ex:'Factories can pollute nearby rivers.',th:'환경·기후'},
  {w:'survive',pos:'v',m:'생존하다',ex:'Plants cannot survive without water.',th:'환경·기후'},
  {w:'destroy',pos:'v',m:'파괴하다',ex:'A fire can destroy a whole forest.',th:'환경·기후'},
  {w:'nature',pos:'n',m:'자연',ex:'They spent the weekend in nature.',th:'환경·기후'},
  {w:'species',pos:'n',m:'종(생물)',ex:'This rare species lives only here.',th:'환경·기후'},
  {w:'atmosphere',pos:'n',m:'대기; 분위기',ex:'Carbon dioxide warms the atmosphere.',th:'환경·기후'},
  {w:'temperature',pos:'n',m:'온도; 기온',ex:'The temperature dropped last night.',th:'환경·기후'},
  {w:'endangered',pos:'a',m:'멸종 위기의',ex:'The panda is an endangered animal.',th:'환경·기후'},
  {w:'waste',pos:'n',m:'쓰레기; 낭비',ex:'The city recycles its waste.',th:'환경·기후'},
  {w:'technology',pos:'n',m:'기술',ex:'Modern technology changes our lives.',th:'과학·기술'},
  {w:'invention',pos:'n',m:'발명(품)',ex:'The wheel was a great invention.',th:'과학·기술'},
  {w:'experiment',pos:'n',m:'실험',ex:'They did an experiment in the lab.',th:'과학·기술'},
  {w:'research',pos:'n',m:'연구',ex:'Her research helped many patients.',th:'과학·기술'},
  {w:'device',pos:'n',m:'장치; 기기',ex:'A phone is a useful device.',th:'과학·기술'},
  {w:'develop',pos:'v',m:'개발하다; 발달하다',ex:'Engineers develop new machines.',th:'과학·기술'},
  {w:'discover',pos:'v',m:'발견하다',ex:'Scientists discover new facts every day.',th:'과학·기술'},
  {w:'invent',pos:'v',m:'발명하다',ex:'People try to invent useful tools.',th:'과학·기술'},
  {w:'connect',pos:'v',m:'연결하다',ex:'The bridge will connect the two towns.',th:'과학·기술'},
  {w:'data',pos:'n',m:'자료; 데이터',ex:'The computer stores a lot of data.',th:'과학·기술'},
  {w:'digital',pos:'a',m:'디지털의',ex:'We live in a digital age.',th:'과학·기술'},
  {w:'artificial',pos:'a',m:'인공의',ex:'Artificial light fills the city at night.',th:'과학·기술'},
  {w:'function',pos:'n',m:'기능',ex:'Each button has a different function.',th:'과학·기술'},
  {w:'system',pos:'n',m:'체계; 시스템',ex:'The school uses a new grading system.',th:'과학·기술'},
  {w:'process',pos:'n',m:'과정',ex:'Learning is a slow process.',th:'과학·기술'},
  {w:'method',pos:'n',m:'방법',ex:'She uses a simple method to study.',th:'과학·기술'},
  {w:'culture',pos:'n',m:'문화',ex:'Food is a big part of culture.',th:'문화·사회'},
  {w:'tradition',pos:'n',m:'전통',ex:'They keep an old family tradition.',th:'문화·사회'},
  {w:'society',pos:'n',m:'사회',ex:'Every society has its own rules.',th:'문화·사회'},
  {w:'custom',pos:'n',m:'관습; 풍습',ex:'Bowing is a common custom here.',th:'문화·사회'},
  {w:'respect',pos:'v',m:'존중하다',ex:'We should respect other cultures.',th:'문화·사회'},
  {w:'community',pos:'n',m:'공동체; 지역사회',ex:'The whole community joined the festival.',th:'문화·사회'},
  {w:'equal',pos:'a',m:'평등한; 동등한',ex:'All people deserve equal rights.',th:'문화·사회'},
  {w:'freedom',pos:'n',m:'자유',ex:'They fought for their freedom.',th:'문화·사회'},
  {w:'peace',pos:'n',m:'평화',ex:'The two nations want peace.',th:'문화·사회'},
  {w:'share',pos:'v',m:'공유하다; 나누다',ex:'Please share the food with others.',th:'문화·사회'},
  {w:'accept',pos:'v',m:'받아들이다',ex:'It is hard to accept a big change.',th:'문화·사회'},
  {w:'behavior',pos:'n',m:'행동',ex:'Kind behavior earns trust.',th:'문화·사회'},
  {w:'value',pos:'n',m:'가치',ex:'Honesty is an important value.',th:'문화·사회'},
  {w:'role',pos:'n',m:'역할',ex:'Parents play a key role in learning.',th:'문화·사회'},
  {w:'support',pos:'v',m:'지지하다; 지원하다',ex:'Good friends support each other.',th:'문화·사회'},
  {w:'generation',pos:'n',m:'세대',ex:'The young generation loves this app.',th:'문화·사회'},
  {w:'health',pos:'n',m:'건강',ex:'Exercise is good for your health.',th:'건강·안전'},
  {w:'exercise',pos:'n',m:'운동',ex:'Daily exercise keeps you strong.',th:'건강·안전'},
  {w:'disease',pos:'n',m:'질병',ex:'Clean water prevents disease.',th:'건강·안전'},
  {w:'medicine',pos:'n',m:'약; 의학',ex:'Take this medicine after meals.',th:'건강·안전'},
  {w:'injury',pos:'n',m:'부상',ex:'He missed the game due to an injury.',th:'건강·안전'},
  {w:'recover',pos:'v',m:'회복하다',ex:'It takes time to recover from a cold.',th:'건강·안전'},
  {w:'prevent',pos:'v',m:'예방하다; 막다',ex:'Washing hands can prevent illness.',th:'건강·안전'},
  {w:'treat',pos:'v',m:'치료하다; 대하다',ex:'Doctors treat sick people.',th:'건강·안전'},
  {w:'safety',pos:'n',m:'안전',ex:'Wear a helmet for your safety.',th:'건강·안전'},
  {w:'dangerous',pos:'a',m:'위험한',ex:'Driving too fast is dangerous.',th:'건강·안전'},
  {w:'breathe',pos:'v',m:'숨쉬다',ex:'It is hard to breathe in thin air.',th:'건강·안전'},
  {w:'muscle',pos:'n',m:'근육',ex:'Regular exercise makes your muscle stronger.',th:'건강·안전'},
  {w:'rest',pos:'n',m:'휴식',ex:'Your body needs enough rest.',th:'건강·안전'},
  {w:'habit',pos:'n',m:'습관',ex:'Reading is a good habit.',th:'건강·안전'},
  {w:'balance',pos:'n',m:'균형',ex:'A good diet keeps a healthy balance.',th:'건강·안전'},
  {w:'nutrition',pos:'n',m:'영양',ex:'Fruit gives good nutrition.',th:'건강·안전'},
  {w:'communicate',pos:'v',m:'의사소통하다',ex:'We use language to communicate.',th:'소통·관계'},
  {w:'relationship',pos:'n',m:'관계',ex:'Trust builds a strong relationship.',th:'소통·관계'},
  {w:'argue',pos:'v',m:'논쟁하다; 주장하다',ex:'They often argue about small things.',th:'소통·관계'},
  {w:'apologize',pos:'v',m:'사과하다',ex:'You should apologize for being late.',th:'소통·관계'},
  {w:'cooperate',pos:'v',m:'협력하다',ex:'The teams must cooperate to win.',th:'소통·관계'},
  {w:'conflict',pos:'n',m:'갈등',ex:'Talking can solve a conflict.',th:'소통·관계'},
  {w:'opinion',pos:'n',m:'의견',ex:'Everyone shared an honest opinion.',th:'소통·관계'},
  {w:'agree',pos:'v',m:'동의하다',ex:'I agree with your plan.',th:'소통·관계'},
  {w:'discuss',pos:'v',m:'논의하다',ex:'Let us discuss the problem together.',th:'소통·관계'},
  {w:'suggest',pos:'v',m:'제안하다',ex:'May I suggest a better idea.',th:'소통·관계'},
  {w:'explain',pos:'v',m:'설명하다',ex:'Please explain the rule again.',th:'소통·관계'},
  {w:'describe',pos:'v',m:'묘사하다',ex:'Can you describe the man you saw.',th:'소통·관계'},
  {w:'trust',pos:'n',m:'신뢰',ex:'A good friendship needs trust.',th:'소통·관계'},
  {w:'honest',pos:'a',m:'정직한',ex:'An honest answer is always best.',th:'소통·관계'},
  {w:'polite',pos:'a',m:'예의 바른',ex:'She gave a polite reply.',th:'소통·관계'},
  {w:'friendship',pos:'n',m:'우정',ex:'Their friendship lasted many years.',th:'소통·관계'},
];
