/* WordQuest — 고1 공통영어·수능 기초 필수 어휘 팩(주제별 큐레이션).
   특정 출판사 교과서 목록이 아니라, 여러 교과서·수능에 반복 출현하는 핵심 어휘를 주제별로 선별한 세트.
   형식: {w, pos, m, ex, th(주제)}. 예문은 원형 포함(cloze 출제 가능). index.html 로직과 분리된 데이터. */
window.WORDPACK_HS1 = [
  {w:'confident',pos:'a',m:'자신 있는',ex:'She felt confident before the big test.',th:'자아·감정'},
  {w:'anxious',pos:'a',m:'불안한',ex:'He was anxious about the exam results.',th:'자아·감정'},
  {w:'grateful',pos:'a',m:'감사하는',ex:'I am grateful for your kind help.',th:'자아·감정'},
  {w:'curious',pos:'a',m:'호기심 있는',ex:'Children are curious about everything around them.',th:'자아·감정'},
  {w:'jealous',pos:'a',m:'질투하는',ex:'He felt jealous when she won the prize.',th:'자아·감정'},
  {w:'shy',pos:'a',m:'수줍은',ex:'The shy boy rarely speaks in class.',th:'자아·감정'},
  {w:'proud',pos:'a',m:'자랑스러운',ex:'They were proud of their small team.',th:'자아·감정'},
  {w:'emotion',pos:'n',m:'감정',ex:'She could not hide her emotion.',th:'자아·감정'},
  {w:'mood',pos:'n',m:'기분',ex:'Good music can change your mood.',th:'자아·감정'},
  {w:'patience',pos:'n',m:'인내심',ex:'Learning a language takes patience.',th:'자아·감정'},
  {w:'confidence',pos:'n',m:'자신감',ex:'Daily practice builds your confidence.',th:'자아·감정'},
  {w:'desire',pos:'n',m:'욕구; 열망',ex:'She has a strong desire to succeed.',th:'자아·감정'},
  {w:'attitude',pos:'n',m:'태도',ex:'A positive attitude helps you grow.',th:'자아·감정'},
  {w:'encourage',pos:'v',m:'격려하다',ex:'Good teachers encourage students to try.',th:'자아·감정'},
  {w:'express',pos:'v',m:'표현하다',ex:'Art lets people express their feelings.',th:'자아·감정'},
  {w:'fear',pos:'n',m:'두려움',ex:'He faced his fear and went on stage.',th:'자아·감정'},
  {w:'achievement',pos:'n',m:'성취; 업적',ex:'Winning the contest was a great achievement.',th:'학교·진로'},
  {w:'effort',pos:'n',m:'노력',ex:'Success comes with steady effort.',th:'학교·진로'},
  {w:'goal',pos:'n',m:'목표',ex:'Set a clear goal for this year.',th:'학교·진로'},
  {w:'career',pos:'n',m:'진로; 경력',ex:'She wants a career in science.',th:'학교·진로'},
  {w:'knowledge',pos:'n',m:'지식',ex:'Reading builds your knowledge.',th:'학교·진로'},
  {w:'skill',pos:'n',m:'기술; 능력',ex:'Writing is an important skill.',th:'학교·진로'},
  {w:'improve',pos:'v',m:'향상시키다',ex:'Practice will improve your English.',th:'학교·진로'},
  {w:'concentrate',pos:'v',m:'집중하다',ex:'Please concentrate on your work.',th:'학교·진로'},
  {w:'graduate',pos:'v',m:'졸업하다',ex:'They will graduate next spring.',th:'학교·진로'},
  {w:'prepare',pos:'v',m:'준비하다',ex:'We should prepare for the exam early.',th:'학교·진로'},
  {w:'challenge',pos:'n',m:'도전',ex:'The new job is a real challenge.',th:'학교·진로'},
  {w:'talent',pos:'n',m:'재능',ex:'She has a talent for music.',th:'학교·진로'},
  {w:'major',pos:'n',m:'전공',ex:'History is her major at college.',th:'학교·진로'},
  {w:'progress',pos:'n',m:'진전; 발전',ex:'You can make good progress with practice.',th:'학교·진로'},
  {w:'motivate',pos:'v',m:'동기를 부여하다',ex:'A clear goal can motivate you.',th:'학교·진로'},
  {w:'succeed',pos:'v',m:'성공하다',ex:'You will succeed if you keep trying.',th:'학교·진로'},
  {w:'environment',pos:'n',m:'환경',ex:'We must protect the environment.',th:'환경·기후'},
  {w:'pollution',pos:'n',m:'오염',ex:'Air pollution is a serious problem.',th:'환경·기후'},
  {w:'climate',pos:'n',m:'기후',ex:'Climate change affects the whole planet.',th:'환경·기후'},
  {w:'resource',pos:'n',m:'자원',ex:'Water is a precious resource.',th:'환경·기후'},
  {w:'protect',pos:'v',m:'보호하다',ex:'We should protect endangered animals.',th:'환경·기후'},
  {w:'reduce',pos:'v',m:'줄이다',ex:'Please reduce your plastic use.',th:'환경·기후'},
  {w:'recycle',pos:'v',m:'재활용하다',ex:'We recycle paper and cans at home.',th:'환경·기후'},
  {w:'pollute',pos:'v',m:'오염시키다',ex:'Factories can pollute nearby rivers.',th:'환경·기후'},
  {w:'survive',pos:'v',m:'생존하다',ex:'Plants cannot survive without water.',th:'환경·기후'},
  {w:'destroy',pos:'v',m:'파괴하다',ex:'A fire can destroy a whole forest.',th:'환경·기후'},
  {w:'nature',pos:'n',m:'자연',ex:'They spent the weekend in nature.',th:'환경·기후'},
  {w:'species',pos:'n',m:'종(생물)',ex:'This rare species lives only here.',th:'환경·기후'},
  {w:'atmosphere',pos:'n',m:'대기; 분위기',ex:'Carbon dioxide warms the atmosphere.',th:'환경·기후'},
  {w:'temperature',pos:'n',m:'온도; 기온',ex:'The temperature dropped last night.',th:'환경·기후'},
  {w:'endangered',pos:'a',m:'멸종 위기의',ex:'The panda is an endangered animal.',th:'환경·기후'},
  {w:'waste',pos:'n',m:'쓰레기; 낭비',ex:'The city recycles its waste.',th:'환경·기후'},
  {w:'technology',pos:'n',m:'기술',ex:'Modern technology changes our lives.',th:'과학·기술'},
  {w:'invention',pos:'n',m:'발명(품)',ex:'The wheel was a great invention.',th:'과학·기술'},
  {w:'experiment',pos:'n',m:'실험',ex:'They did an experiment in the lab.',th:'과학·기술'},
  {w:'research',pos:'n',m:'연구',ex:'Her research helped many patients.',th:'과학·기술'},
  {w:'device',pos:'n',m:'장치; 기기',ex:'A phone is a useful device.',th:'과학·기술'},
  {w:'develop',pos:'v',m:'개발하다; 발달하다',ex:'Engineers develop new machines.',th:'과학·기술'},
  {w:'discover',pos:'v',m:'발견하다',ex:'Scientists discover new facts every day.',th:'과학·기술'},
  {w:'invent',pos:'v',m:'발명하다',ex:'People try to invent useful tools.',th:'과학·기술'},
  {w:'connect',pos:'v',m:'연결하다',ex:'The bridge will connect the two towns.',th:'과학·기술'},
  {w:'data',pos:'n',m:'자료; 데이터',ex:'The computer stores a lot of data.',th:'과학·기술'},
  {w:'digital',pos:'a',m:'디지털의',ex:'We live in a digital age.',th:'과학·기술'},
  {w:'artificial',pos:'a',m:'인공의',ex:'Artificial light fills the city at night.',th:'과학·기술'},
  {w:'function',pos:'n',m:'기능',ex:'Each button has a different function.',th:'과학·기술'},
  {w:'system',pos:'n',m:'체계; 시스템',ex:'The school uses a new grading system.',th:'과학·기술'},
  {w:'process',pos:'n',m:'과정',ex:'Learning is a slow process.',th:'과학·기술'},
  {w:'method',pos:'n',m:'방법',ex:'She uses a simple method to study.',th:'과학·기술'},
  {w:'culture',pos:'n',m:'문화',ex:'Food is a big part of culture.',th:'문화·사회'},
  {w:'tradition',pos:'n',m:'전통',ex:'They keep an old family tradition.',th:'문화·사회'},
  {w:'society',pos:'n',m:'사회',ex:'Every society has its own rules.',th:'문화·사회'},
  {w:'custom',pos:'n',m:'관습; 풍습',ex:'Bowing is a common custom here.',th:'문화·사회'},
  {w:'respect',pos:'v',m:'존중하다',ex:'We should respect other cultures.',th:'문화·사회'},
  {w:'community',pos:'n',m:'공동체; 지역사회',ex:'The whole community joined the festival.',th:'문화·사회'},
  {w:'equal',pos:'a',m:'평등한; 동등한',ex:'All people deserve equal rights.',th:'문화·사회'},
  {w:'freedom',pos:'n',m:'자유',ex:'They fought for their freedom.',th:'문화·사회'},
  {w:'peace',pos:'n',m:'평화',ex:'The two nations want peace.',th:'문화·사회'},
  {w:'share',pos:'v',m:'공유하다; 나누다',ex:'Please share the food with others.',th:'문화·사회'},
  {w:'accept',pos:'v',m:'받아들이다',ex:'It is hard to accept a big change.',th:'문화·사회'},
  {w:'behavior',pos:'n',m:'행동',ex:'Kind behavior earns trust.',th:'문화·사회'},
  {w:'value',pos:'n',m:'가치',ex:'Honesty is an important value.',th:'문화·사회'},
  {w:'role',pos:'n',m:'역할',ex:'Parents play a key role in learning.',th:'문화·사회'},
  {w:'support',pos:'v',m:'지지하다; 지원하다',ex:'Good friends support each other.',th:'문화·사회'},
  {w:'generation',pos:'n',m:'세대',ex:'The young generation loves this app.',th:'문화·사회'},
  {w:'health',pos:'n',m:'건강',ex:'Exercise is good for your health.',th:'건강·안전'},
  {w:'exercise',pos:'n',m:'운동',ex:'Daily exercise keeps you strong.',th:'건강·안전'},
  {w:'disease',pos:'n',m:'질병',ex:'Clean water prevents disease.',th:'건강·안전'},
  {w:'medicine',pos:'n',m:'약; 의학',ex:'Take this medicine after meals.',th:'건강·안전'},
  {w:'injury',pos:'n',m:'부상',ex:'He missed the game due to an injury.',th:'건강·안전'},
  {w:'recover',pos:'v',m:'회복하다',ex:'It takes time to recover from a cold.',th:'건강·안전'},
  {w:'prevent',pos:'v',m:'예방하다; 막다',ex:'Washing hands can prevent illness.',th:'건강·안전'},
  {w:'treat',pos:'v',m:'치료하다; 대하다',ex:'Doctors treat sick people.',th:'건강·안전'},
  {w:'safety',pos:'n',m:'안전',ex:'Wear a helmet for your safety.',th:'건강·안전'},
  {w:'dangerous',pos:'a',m:'위험한',ex:'Driving too fast is dangerous.',th:'건강·안전'},
  {w:'breathe',pos:'v',m:'숨쉬다',ex:'It is hard to breathe in thin air.',th:'건강·안전'},
  {w:'muscle',pos:'n',m:'근육',ex:'Regular exercise makes your muscle stronger.',th:'건강·안전'},
  {w:'rest',pos:'n',m:'휴식',ex:'Your body needs enough rest.',th:'건강·안전'},
  {w:'habit',pos:'n',m:'습관',ex:'Reading is a good habit.',th:'건강·안전'},
  {w:'balance',pos:'n',m:'균형',ex:'A good diet keeps a healthy balance.',th:'건강·안전'},
  {w:'nutrition',pos:'n',m:'영양',ex:'Fruit gives good nutrition.',th:'건강·안전'},
  {w:'communicate',pos:'v',m:'의사소통하다',ex:'We use language to communicate.',th:'소통·관계'},
  {w:'relationship',pos:'n',m:'관계',ex:'Trust builds a strong relationship.',th:'소통·관계'},
  {w:'argue',pos:'v',m:'논쟁하다; 주장하다',ex:'They often argue about small things.',th:'소통·관계'},
  {w:'apologize',pos:'v',m:'사과하다',ex:'You should apologize for being late.',th:'소통·관계'},
  {w:'cooperate',pos:'v',m:'협력하다',ex:'The teams must cooperate to win.',th:'소통·관계'},
  {w:'conflict',pos:'n',m:'갈등',ex:'Talking can solve a conflict.',th:'소통·관계'},
  {w:'opinion',pos:'n',m:'의견',ex:'Everyone shared an honest opinion.',th:'소통·관계'},
  {w:'agree',pos:'v',m:'동의하다',ex:'I agree with your plan.',th:'소통·관계'},
  {w:'discuss',pos:'v',m:'논의하다',ex:'Let us discuss the problem together.',th:'소통·관계'},
  {w:'suggest',pos:'v',m:'제안하다',ex:'May I suggest a better idea.',th:'소통·관계'},
  {w:'explain',pos:'v',m:'설명하다',ex:'Please explain the rule again.',th:'소통·관계'},
  {w:'describe',pos:'v',m:'묘사하다',ex:'Can you describe the man you saw.',th:'소통·관계'},
  {w:'trust',pos:'n',m:'신뢰',ex:'A good friendship needs trust.',th:'소통·관계'},
  {w:'honest',pos:'a',m:'정직한',ex:'An honest answer is always best.',th:'소통·관계'},
  {w:'polite',pos:'a',m:'예의 바른',ex:'She gave a polite reply.',th:'소통·관계'},
  {w:'friendship',pos:'n',m:'우정',ex:'Their friendship lasted many years.',th:'소통·관계'},
  // ── 확장분(시간·경제·여행·예술·사고·성질·도시생활) ──
  {w:'moment',pos:'n',m:'순간',ex:'Please wait for a moment.',th:'시간·변화'},
  {w:'period',pos:'n',m:'기간; 시기',ex:'This is a busy period for farmers.',th:'시간·변화'},
  {w:'decade',pos:'n',m:'십 년',ex:'The town grew fast over the last decade.',th:'시간·변화'},
  {w:'century',pos:'n',m:'세기; 100년',ex:'The castle is over a century old.',th:'시간·변화'},
  {w:'recent',pos:'a',m:'최근의',ex:'A recent study surprised many people.',th:'시간·변화'},
  {w:'constant',pos:'a',m:'끊임없는; 일정한',ex:'The engine makes a constant noise.',th:'시간·변화'},
  {w:'sudden',pos:'a',m:'갑작스러운',ex:'There was a sudden change in plans.',th:'시간·변화'},
  {w:'delay',pos:'v',m:'지연시키다',ex:'Heavy snow may delay the train.',th:'시간·변화'},
  {w:'remain',pos:'v',m:'남다; 여전히 ~이다',ex:'Only a few seats remain.',th:'시간·변화'},
  {w:'continue',pos:'v',m:'계속하다',ex:'They will continue the game after lunch.',th:'시간·변화'},
  {w:'occur',pos:'v',m:'일어나다; 발생하다',ex:'Storms occur here every summer.',th:'시간·변화'},
  {w:'former',pos:'a',m:'이전의',ex:'The former leader moved abroad.',th:'시간·변화'},
  {w:'current',pos:'a',m:'현재의',ex:'The current plan needs more time.',th:'시간·변화'},
  {w:'forever',pos:'ad',m:'영원히',ex:'No one can live forever.',th:'시간·변화'},
  {w:'permanent',pos:'a',m:'영구적인',ex:'They finally found a permanent home.',th:'시간·변화'},
  {w:'schedule',pos:'n',m:'일정',ex:'Check the schedule before you leave.',th:'시간·변화'},
  {w:'economy',pos:'n',m:'경제',ex:'The economy grew last year.',th:'경제·소비'},
  {w:'budget',pos:'n',m:'예산',ex:'The family made a monthly budget.',th:'경제·소비'},
  {w:'cost',pos:'n',m:'비용',ex:'The cost of the trip is high.',th:'경제·소비'},
  {w:'price',pos:'n',m:'가격',ex:'The price of oil went up.',th:'경제·소비'},
  {w:'profit',pos:'n',m:'이익',ex:'The shop made a small profit.',th:'경제·소비'},
  {w:'product',pos:'n',m:'제품',ex:'This product sells very well.',th:'경제·소비'},
  {w:'customer',pos:'n',m:'고객',ex:'The customer asked for a refund.',th:'경제·소비'},
  {w:'purchase',pos:'v',m:'구매하다',ex:'You can purchase tickets online.',th:'경제·소비'},
  {w:'afford',pos:'v',m:'~할 여유가 있다',ex:'They cannot afford a new car.',th:'경제·소비'},
  {w:'spend',pos:'v',m:'(돈·시간을) 쓰다',ex:'Do not spend too much money.',th:'경제·소비'},
  {w:'wealth',pos:'n',m:'부; 재산',ex:'Health matters more than wealth.',th:'경제·소비'},
  {w:'trade',pos:'n',m:'무역; 거래',ex:'The two countries increased trade.',th:'경제·소비'},
  {w:'demand',pos:'n',m:'수요; 요구',ex:'The demand for water rose in summer.',th:'경제·소비'},
  {w:'supply',pos:'n',m:'공급',ex:'The water supply is low.',th:'경제·소비'},
  {w:'expensive',pos:'a',m:'비싼',ex:'The watch is too expensive.',th:'경제·소비'},
  {w:'income',pos:'n',m:'소득',ex:'They live on a small income.',th:'경제·소비'},
  {w:'journey',pos:'n',m:'여정',ex:'They began a long journey.',th:'여행·모험'},
  {w:'adventure',pos:'n',m:'모험',ex:'The trip was a great adventure.',th:'여행·모험'},
  {w:'destination',pos:'n',m:'목적지',ex:'We reached our destination at noon.',th:'여행·모험'},
  {w:'explore',pos:'v',m:'탐험하다',ex:'They love to explore old towns.',th:'여행·모험'},
  {w:'arrive',pos:'v',m:'도착하다',ex:'We will arrive before dark.',th:'여행·모험'},
  {w:'depart',pos:'v',m:'출발하다',ex:'The plane will depart at noon.',th:'여행·모험'},
  {w:'abroad',pos:'ad',m:'해외로',ex:'She wants to study abroad.',th:'여행·모험'},
  {w:'foreign',pos:'a',m:'외국의',ex:'He is learning a foreign language.',th:'여행·모험'},
  {w:'passport',pos:'n',m:'여권',ex:'Do not forget your passport.',th:'여행·모험'},
  {w:'luggage',pos:'n',m:'짐; 수하물',ex:'Please carry your own luggage.',th:'여행·모험'},
  {w:'tourist',pos:'n',m:'관광객',ex:'A tourist asked me for directions.',th:'여행·모험'},
  {w:'distance',pos:'n',m:'거리',ex:'They walked a long distance.',th:'여행·모험'},
  {w:'route',pos:'n',m:'경로',ex:'We took a shorter route home.',th:'여행·모험'},
  {w:'local',pos:'a',m:'지역의; 현지의',ex:'We ate at a local restaurant.',th:'여행·모험'},
  {w:'wander',pos:'v',m:'거닐다; 헤매다',ex:'They wander around the old market.',th:'여행·모험'},
  {w:'guide',pos:'n',m:'안내자; 안내서',ex:'A local guide showed us the way.',th:'여행·모험'},
  {w:'art',pos:'n',m:'예술; 미술',ex:'She studies modern art.',th:'예술·표현'},
  {w:'artist',pos:'n',m:'예술가',ex:'The artist painted a huge wall.',th:'예술·표현'},
  {w:'create',pos:'v',m:'창조하다; 만들다',ex:'They create beautiful songs.',th:'예술·표현'},
  {w:'imagine',pos:'v',m:'상상하다',ex:'Try to imagine a better world.',th:'예술·표현'},
  {w:'imagination',pos:'n',m:'상상력',ex:'A child has rich imagination.',th:'예술·표현'},
  {w:'design',pos:'n',m:'디자인; 설계',ex:'The design of the car is new.',th:'예술·표현'},
  {w:'perform',pos:'v',m:'공연하다; 수행하다',ex:'The band will perform tonight.',th:'예술·표현'},
  {w:'audience',pos:'n',m:'관객; 청중',ex:'The audience clapped loudly.',th:'예술·표현'},
  {w:'creative',pos:'a',m:'창의적인',ex:'She has a creative mind.',th:'예술·표현'},
  {w:'instrument',pos:'n',m:'악기; 도구',ex:'The piano is a large instrument.',th:'예술·표현'},
  {w:'paint',pos:'v',m:'그리다; 칠하다',ex:'They paint the fence every spring.',th:'예술·표현'},
  {w:'draw',pos:'v',m:'그리다; 끌다',ex:'Children love to draw animals.',th:'예술·표현'},
  {w:'novel',pos:'n',m:'소설',ex:'She wrote a famous novel.',th:'예술·표현'},
  {w:'scene',pos:'n',m:'장면',ex:'The last scene made me cry.',th:'예술·표현'},
  {w:'impress',pos:'v',m:'감명을 주다',ex:'Her speech will impress the judges.',th:'예술·표현'},
  {w:'style',pos:'n',m:'양식; 방식',ex:'I like her writing style.',th:'예술·표현'},
  {w:'decide',pos:'v',m:'결정하다',ex:'You must decide soon.',th:'사고·판단'},
  {w:'decision',pos:'n',m:'결정',ex:'It was a hard decision.',th:'사고·판단'},
  {w:'consider',pos:'v',m:'고려하다',ex:'Please consider my idea.',th:'사고·판단'},
  {w:'judge',pos:'v',m:'판단하다',ex:'Do not judge people by looks.',th:'사고·판단'},
  {w:'compare',pos:'v',m:'비교하다',ex:'Compare the two plans first.',th:'사고·판단'},
  {w:'realize',pos:'v',m:'깨닫다',ex:'She did not realize the time.',th:'사고·판단'},
  {w:'doubt',pos:'n',m:'의심',ex:'I have no doubt about it.',th:'사고·판단'},
  {w:'reason',pos:'n',m:'이유; 이성',ex:'Give me a good reason.',th:'사고·판단'},
  {w:'focus',pos:'v',m:'집중하다',ex:'Please focus on one task.',th:'사고·판단'},
  {w:'solve',pos:'v',m:'해결하다',ex:'We must solve this problem.',th:'사고·판단'},
  {w:'predict',pos:'v',m:'예측하다',ex:'No one can predict the future.',th:'사고·판단'},
  {w:'conclude',pos:'v',m:'결론짓다',ex:'We can conclude the meeting now.',th:'사고·판단'},
  {w:'purpose',pos:'n',m:'목적',ex:'What is the purpose of this rule?',th:'사고·판단'},
  {w:'wonder',pos:'v',m:'궁금해하다',ex:'I wonder where she went.',th:'사고·판단'},
  {w:'recognize',pos:'v',m:'알아보다; 인정하다',ex:'I did not recognize you at first.',th:'사고·판단'},
  {w:'aware',pos:'a',m:'알고 있는; 인식하는',ex:'She is aware of the danger.',th:'사고·판단'},
  {w:'huge',pos:'a',m:'거대한',ex:'They live in a huge house.',th:'성질·정도'},
  {w:'tiny',pos:'a',m:'아주 작은',ex:'A tiny insect sat on the leaf.',th:'성질·정도'},
  {w:'various',pos:'a',m:'다양한',ex:'The shop sells various goods.',th:'성질·정도'},
  {w:'similar',pos:'a',m:'비슷한',ex:'The twins wear similar clothes.',th:'성질·정도'},
  {w:'familiar',pos:'a',m:'익숙한',ex:'The song sounds familiar.',th:'성질·정도'},
  {w:'common',pos:'a',m:'흔한; 공통의',ex:'Rain is common in this season.',th:'성질·정도'},
  {w:'rare',pos:'a',m:'드문; 희귀한',ex:'This is a rare bird.',th:'성질·정도'},
  {w:'complex',pos:'a',m:'복잡한',ex:'The machine has a complex design.',th:'성질·정도'},
  {w:'obvious',pos:'a',m:'명백한',ex:'The answer is obvious.',th:'성질·정도'},
  {w:'specific',pos:'a',m:'구체적인; 특정한',ex:'Give me a specific example.',th:'성질·정도'},
  {w:'minor',pos:'a',m:'사소한; 작은',ex:'It was only a minor mistake.',th:'성질·정도'},
  {w:'sufficient',pos:'a',m:'충분한',ex:'We have sufficient food for the trip.',th:'성질·정도'},
  {w:'essential',pos:'a',m:'필수적인',ex:'Water is essential for life.',th:'성질·정도'},
  {w:'valuable',pos:'a',m:'귀중한',ex:'Time is valuable.',th:'성질·정도'},
  {w:'complete',pos:'a',m:'완전한',ex:'This is a complete list.',th:'성질·정도'},
  {w:'flexible',pos:'a',m:'유연한',ex:'Our schedule is flexible.',th:'성질·정도'},
  {w:'population',pos:'n',m:'인구',ex:'The population of the city keeps growing.',th:'도시·생활'},
  {w:'traffic',pos:'n',m:'교통(량)',ex:'The traffic was heavy this morning.',th:'도시·생활'},
  {w:'public',pos:'a',m:'공공의; 대중의',ex:'They met in a public park.',th:'도시·생활'},
  {w:'private',pos:'a',m:'사적인; 개인의',ex:'This is a private matter.',th:'도시·생활'},
  {w:'neighbor',pos:'n',m:'이웃',ex:'My neighbor has a big dog.',th:'도시·생활'},
  {w:'citizen',pos:'n',m:'시민',ex:'Every citizen can vote.',th:'도시·생활'},
  {w:'government',pos:'n',m:'정부',ex:'The government built a new road.',th:'도시·생활'},
  {w:'crime',pos:'n',m:'범죄',ex:'The police stopped a crime.',th:'도시·생활'},
  {w:'rule',pos:'n',m:'규칙',ex:'Please follow the rule.',th:'도시·생활'},
  {w:'service',pos:'n',m:'서비스; 봉사',ex:'The hotel offers great service.',th:'도시·생활'},
  {w:'transport',pos:'v',m:'수송하다',ex:'Buses transport many people daily.',th:'도시·생활'},
  {w:'facility',pos:'n',m:'시설',ex:'The school has a new sports facility.',th:'도시·생활'},
  {w:'crowd',pos:'n',m:'군중',ex:'A large crowd filled the square.',th:'도시·생활'},
  {w:'available',pos:'a',m:'이용 가능한',ex:'Tickets are available online.',th:'도시·생활'},
  {w:'convenient',pos:'a',m:'편리한',ex:'The new app is very convenient.',th:'도시·생활'},
  {w:'modern',pos:'a',m:'현대의',ex:'They live in a modern city.',th:'도시·생활'},
];
