/* WordQuest 단어은행 — 고1 공통·수능 기초 고빈도 어휘 + 예문.
   형식: {w:영어, pos:품사(v/n/a/ad), m:한국어뜻(다의어는 ; 로 구분), ex:예문, ex2:(선택)두번째뜻 예문}
   교과서 단어는 여기에 한 줄씩 추가하면 앱에 자동 반영됩니다. index.html 로직과 분리된 데이터 파일.
   예문은 대상 단어의 원형을 그대로 포함해야 빈칸(cloze) 출제에 쓰입니다. */
window.WORDBANK = [
  {w:'abandon',pos:'v',m:'버리다; 포기하다',ex:'They had to abandon the old house.',ex2:'Never abandon hope.'},
  {w:'achieve',pos:'v',m:'성취하다',ex:'You can achieve your dreams with effort.'},
  {w:'abundant',pos:'a',m:'풍부한',ex:'The region has abundant natural resources.'},
  {w:'accurate',pos:'a',m:'정확한',ex:'We need an accurate measurement.'},
  {w:'adapt',pos:'v',m:'적응하다',ex:'Animals must adapt to their environment.'},
  {w:'admire',pos:'v',m:'감탄하다',ex:'I really admire her courage.'},
  {w:'forbid',pos:'v',m:'금지하다',ex:'The rules forbid running near the pool.'},
  {w:'courage',pos:'n',m:'용기',ex:'It takes courage to tell the truth.'},
  {w:'delicate',pos:'a',m:'섬세한',ex:'The old vase is very delicate.'},
  {w:'enthusiasm',pos:'n',m:'열정',ex:'She spoke with great enthusiasm.'},
  {w:'expand',pos:'v',m:'확장하다; 팽창하다',ex:'The company plans to expand its business.',ex2:'Metals expand when they are heated.'},
  {w:'fragile',pos:'a',m:'연약한',ex:'Please be careful; the box is fragile.'},
  {w:'hesitate',pos:'v',m:'머뭇거리다',ex:"Don't hesitate to ask for help."},
  {w:'negotiate',pos:'v',m:'협상하다',ex:'The two sides will negotiate a deal.'},
  {w:'overcome',pos:'v',m:'극복하다',ex:'He worked hard to overcome his fear.'},
  {w:'persuade',pos:'v',m:'설득하다',ex:'I tried to persuade him to stay.'},
  {w:'recover',pos:'v',m:'회복하다; 되찾다',ex:'It took her a week to recover from the flu.',ex2:'The police helped him recover his stolen bike.'},
  {w:'sacrifice',pos:'v',m:'희생하다',ex:'Parents often sacrifice a lot for their children.'},
  {w:'temporary',pos:'a',m:'일시적인',ex:'This is only a temporary solution.'},
  {w:'witness',pos:'v',m:'목격하다; 증인',ex:'Did anyone witness the accident?',ex2:'The witness described the suspect to the police.'},
  {w:'ancient',pos:'a',m:'고대의',ex:'They discovered an ancient temple.'},
  {w:'appreciate',pos:'v',m:'감사하다; 진가를 알다',ex:'I appreciate your help.',ex2:'Few people appreciate good art.'},
  {w:'assume',pos:'v',m:'가정하다',ex:"Let's not assume the worst."},
  {w:'avoid',pos:'v',m:'피하다',ex:'Try to avoid junk food.'},
  {w:'benefit',pos:'n',m:'이익; 이롭게 하다',ex:'The main benefit is a lower cost.',ex2:'The new law will benefit small farms.'},
  {w:'consider',pos:'v',m:'고려하다',ex:'Please consider my suggestion.'},
  {w:'constant',pos:'a',m:'끊임없는; 상수',ex:'The baby needs constant care.',ex2:'In this formula, c is a constant.'},
  {w:'contribute',pos:'v',m:'기여하다',ex:'Everyone should contribute to the team.'},
  {w:'convince',pos:'v',m:'확신시키다',ex:'She managed to convince us.'},
  {w:'decline',pos:'v',m:'감소하다; 거절하다',ex:'Sales began to decline last year.',ex2:'She had to decline the invitation.'},
  {w:'dedicate',pos:'v',m:'헌신하다',ex:'He decided to dedicate his life to science.'},
  {w:'defeat',pos:'v',m:'패배시키다',ex:'Our team hopes to defeat the champions.'},
  {w:'demand',pos:'v',m:'요구하다; 수요',ex:'The workers demand higher pay.',ex2:'There is high demand for clean energy.'},
  {w:'deny',pos:'v',m:'부인하다',ex:'He did not deny the mistake.'},
  {w:'distinguish',pos:'v',m:'구별하다',ex:'It is hard to distinguish the twins.'},
  {w:'efficient',pos:'a',m:'효율적인',ex:'We need a more efficient system.'},
  {w:'eliminate',pos:'v',m:'제거하다',ex:'We must eliminate the errors.'},
  {w:'emphasize',pos:'v',m:'강조하다',ex:'Teachers often emphasize practice.'},
  {w:'encounter',pos:'v',m:'마주치다',ex:'You may encounter problems at first.'},
  {w:'ensure',pos:'v',m:'보장하다',ex:'Please ensure the door is locked.'},
  {w:'essential',pos:'a',m:'필수적인',ex:'Water is essential for life.'},
  {w:'estimate',pos:'v',m:'추정하다',ex:'Experts estimate the cost at five hundred dollars.'},
  {w:'exhaust',pos:'v',m:'지치게 하다',ex:'The long trip will exhaust the children.'},
  {w:'generate',pos:'v',m:'발생시키다',ex:'The plant can generate electricity.'},
  {w:'genuine',pos:'a',m:'진짜의',ex:'This is a genuine diamond.'},
  {w:'gradual',pos:'a',m:'점진적인',ex:'There was a gradual change in the weather.'},
  {w:'humble',pos:'a',m:'겸손한; 초라한',ex:'Despite his fame, he stayed humble.',ex2:'They lived in a humble little house.'},
  {w:'ignore',pos:'v',m:'무시하다',ex:'Do not ignore the warning signs.'},
  {w:'imitate',pos:'v',m:'모방하다',ex:'Children often imitate adults.'},
  {w:'indicate',pos:'v',m:'나타내다',ex:'The results indicate a problem.'},
  {w:'inevitable',pos:'a',m:'불가피한',ex:'Change is inevitable.'},
  {w:'interpret',pos:'v',m:'해석하다; 통역하다',ex:'How do you interpret this poem?',ex2:'She will interpret for the foreign visitors.'},
  {w:'maintain',pos:'v',m:'유지하다; 주장하다',ex:'It is important to maintain good health.',ex2:'He continued to maintain that he was innocent.'},
  {w:'obvious',pos:'a',m:'명백한',ex:'The answer is obvious.'},
  {w:'participate',pos:'v',m:'참여하다',ex:'Everyone can participate in the event.'},
  {w:'postpone',pos:'v',m:'연기하다',ex:'We had to postpone the meeting.'},
  {w:'pretend',pos:'v',m:'~인 척하다',ex:'He likes to pretend to be a hero.'},
  {w:'prevent',pos:'v',m:'예방하다',ex:'Vaccines help prevent disease.'},
  {w:'reject',pos:'v',m:'거절하다',ex:'They may reject the offer.'},
  {w:'reluctant',pos:'a',m:'꺼리는',ex:'She was reluctant to leave.'},
  {w:'remove',pos:'v',m:'제거하다',ex:'Please remove your shoes.'},
  {w:'reveal',pos:'v',m:'드러내다; 폭로하다',ex:'The report will reveal the truth.',ex2:'The reporter promised to reveal the scandal.'},
  {w:'significant',pos:'a',m:'중요한',ex:'This is a significant discovery.'},
  {w:'absorb',pos:'v',m:'흡수하다',ex:'Plants absorb water through their roots.'},
  {w:'abstract',pos:'a',m:'추상적인',ex:'Art can be very abstract.'},
  {w:'accompany',pos:'v',m:'동반하다',ex:'She will accompany her father to the clinic.'},
  {w:'accomplish',pos:'v',m:'해내다',ex:'He hopes to accomplish his goal.'},
  {w:'accuse',pos:'v',m:'고발하다',ex:'They accuse him of cheating.'},
  {w:'acquire',pos:'v',m:'습득하다',ex:'Children acquire language quickly.'},
  {w:'adequate',pos:'a',m:'적절한',ex:'We have adequate supplies.'},
  {w:'adjust',pos:'v',m:'조정하다',ex:'You can adjust the volume.'},
  {w:'admit',pos:'v',m:'인정하다',ex:'He will admit his mistake.'},
  {w:'adopt',pos:'v',m:'채택하다',ex:'The school may adopt a new rule.'},
  {w:'afford',pos:'v',m:'~할 여유가 있다',ex:'I cannot afford a new phone.'},
  {w:'aggressive',pos:'a',m:'공격적인',ex:'The dog looked aggressive.'},
  {w:'alter',pos:'v',m:'바꾸다',ex:'We had to alter the plan.'},
  {w:'amaze',pos:'v',m:'놀라게 하다',ex:'The trick will amaze the kids.'},
  {w:'ambition',pos:'n',m:'야망',ex:'She has great ambition.'},
  {w:'amount',pos:'n',m:'양',ex:'A huge amount of food was wasted.'},
  {w:'analyze',pos:'v',m:'분석하다',ex:'Scientists analyze the data.'},
  {w:'annoy',pos:'v',m:'짜증나게 하다',ex:'Loud noise can annoy people.'},
  {w:'anticipate',pos:'v',m:'예상하다',ex:'We anticipate a busy day.'},
  {w:'anxiety',pos:'n',m:'불안',ex:'He felt deep anxiety.'},
  {w:'apologize',pos:'v',m:'사과하다',ex:'You should apologize to her.'},
  {w:'apparent',pos:'a',m:'명백한',ex:'The error was apparent.'},
  {w:'appeal',pos:'v',m:'호소하다',ex:'They appeal for help.'},
  {w:'appropriate',pos:'a',m:'적절한',ex:'Please wear appropriate clothes.'},
  {w:'approve',pos:'v',m:'승인하다',ex:'The boss will approve the plan.'},
  {w:'argue',pos:'v',m:'논쟁하다',ex:'They often argue about money.'},
  {w:'arrange',pos:'v',m:'정리하다',ex:'Please arrange the chairs.'},
  {w:'ashamed',pos:'a',m:'부끄러운',ex:'He felt ashamed of the lie.'},
  {w:'assess',pos:'v',m:'평가하다',ex:'Teachers assess student progress.'},
  {w:'assign',pos:'v',m:'할당하다',ex:'The teacher will assign homework.'},
  {w:'assist',pos:'v',m:'돕다',ex:'Nurses assist the doctor.'},
  {w:'associate',pos:'v',m:'연관짓다',ex:'We associate summer with the beach.'},
  {w:'attach',pos:'v',m:'붙이다',ex:'Please attach the file.'},
  {w:'attempt',pos:'v',m:'시도하다',ex:'He will attempt the climb.'},
  {w:'attitude',pos:'n',m:'태도',ex:'Keep a positive attitude.'},
  {w:'attract',pos:'v',m:'끌어당기다',ex:'Flowers attract bees.'},
  {w:'authority',pos:'n',m:'권위',ex:'The police have authority here.'},
  {w:'available',pos:'a',m:'이용 가능한',ex:'The book is available online.'},
  {w:'aware',pos:'a',m:'알고 있는',ex:'Be aware of the danger.'},
  {w:'awkward',pos:'a',m:'어색한',ex:'There was an awkward silence.'},
  {w:'barely',pos:'ad',m:'간신히',ex:'He could barely walk.'},
  {w:'bargain',pos:'n',m:'싼 물건',ex:'This coat was a real bargain.'},
  {w:'betray',pos:'v',m:'배신하다',ex:'He would never betray a friend.'},
  {w:'blame',pos:'v',m:'비난하다',ex:'Do not blame others.'},
  {w:'boast',pos:'v',m:'자랑하다',ex:'He likes to boast about his car.'},
  {w:'bother',pos:'v',m:'귀찮게 하다',ex:'Do not bother your sister.'},
  {w:'brief',pos:'a',m:'간단한',ex:'He gave a brief speech.'},
  {w:'broad',pos:'a',m:'넓은',ex:'The river is very broad.'},
  {w:'burden',pos:'n',m:'부담',ex:'The debt was a heavy burden.'},
  {w:'calculate',pos:'v',m:'계산하다',ex:'Please calculate the total.'},
  {w:'capable',pos:'a',m:'유능한',ex:'She is capable of great work.'},
  {w:'casual',pos:'a',m:'격식 없는',ex:'Wear casual clothes to the party.'},
  {w:'cease',pos:'v',m:'중단하다',ex:'The rain will cease soon.'},
  {w:'celebrate',pos:'v',m:'축하하다',ex:'We celebrate her birthday today.'},
  {w:'challenge',pos:'n',m:'도전',ex:'Learning a language is a challenge.'},
  {w:'cherish',pos:'v',m:'소중히 하다',ex:'I cherish these memories.'},
  {w:'cite',pos:'v',m:'인용하다',ex:'The writer will cite a study.'},
  {w:'claim',pos:'v',m:'주장하다',ex:'He will claim the prize.'},
  {w:'clarify',pos:'v',m:'명확히 하다',ex:'Let me clarify my point.'},
  {w:'classify',pos:'v',m:'분류하다',ex:'We classify animals into groups.'},
  {w:'clue',pos:'n',m:'단서',ex:'The detective found a clue.'},
  {w:'collapse',pos:'v',m:'붕괴하다',ex:'The old bridge could collapse.'},
  {w:'colleague',pos:'n',m:'동료',ex:'She is my colleague.'},
  {w:'combine',pos:'v',m:'결합하다',ex:'Please combine the flour and sugar.'},
  {w:'commit',pos:'v',m:'저지르다',ex:'He would never commit a crime.'},
  {w:'companion',pos:'n',m:'동반자',ex:'A dog is a loyal companion.'},
  {w:'compare',pos:'v',m:'비교하다',ex:'Please compare the two answers.'},
  {w:'compensate',pos:'v',m:'보상하다',ex:'They will compensate the workers.'},
  {w:'compete',pos:'v',m:'경쟁하다',ex:'Many students compete for the prize.'},
  {w:'complain',pos:'v',m:'불평하다',ex:'Customers often complain about delays.'},
  {w:'complex',pos:'a',m:'복잡한',ex:'This is a complex problem.'},
  {w:'component',pos:'n',m:'구성 요소',ex:'Each component has a purpose.'},
  {w:'compose',pos:'v',m:'작곡하다',ex:'She will compose a song.'},
  {w:'comprehend',pos:'v',m:'이해하다',ex:'It is hard to comprehend the theory.'},
  {w:'conceal',pos:'v',m:'숨기다',ex:'He tried to conceal the truth.'},
  {w:'concentrate',pos:'v',m:'집중하다',ex:'Please concentrate on your work.'},
  {w:'conclude',pos:'v',m:'결론짓다',ex:'The report will conclude with advice.'},
  {w:'confess',pos:'v',m:'고백하다',ex:'He decided to confess the truth.'},
  {w:'confident',pos:'a',m:'자신 있는',ex:'She feels confident about the exam.'},
  {w:'confirm',pos:'v',m:'확인하다',ex:'Please confirm your booking.'},
  {w:'conflict',pos:'n',m:'갈등',ex:'There was a conflict between them.'},
  {w:'confront',pos:'v',m:'맞서다',ex:'We must confront the problem.'},
  {w:'confuse',pos:'v',m:'혼란시키다',ex:'The signs confuse many drivers.'},
  {w:'congratulate',pos:'v',m:'축하하다',ex:'I want to congratulate you.'},
  {w:'conquer',pos:'v',m:'정복하다',ex:'The king wanted to conquer new lands.'},
  {w:'conscience',pos:'n',m:'양심',ex:'His conscience troubled him.'},
  {w:'consequence',pos:'n',m:'결과',ex:'Every action has a consequence.'},
  {w:'conserve',pos:'v',m:'보존하다',ex:'We must conserve water.'},
  {w:'construct',pos:'v',m:'건설하다',ex:'They will construct a bridge.'},
  {w:'consult',pos:'v',m:'상담하다',ex:'You should consult a doctor.'},
  {w:'consume',pos:'v',m:'소비하다',ex:'Cars consume a lot of fuel.'},
  {w:'contain',pos:'v',m:'포함하다',ex:'These boxes contain books.'},
  {w:'context',pos:'n',m:'맥락',ex:'Words have meaning in context.'},
  {w:'continent',pos:'n',m:'대륙',ex:'Africa is a large continent.'},
  {w:'convert',pos:'v',m:'전환하다',ex:'They convert sunlight into power.'},
  {w:'convey',pos:'v',m:'전달하다',ex:'Words convey meaning.'},
  {w:'cooperate',pos:'v',m:'협력하다',ex:'We must cooperate to win.'},
  {w:'cope',pos:'v',m:'대처하다',ex:'She can cope with stress.'},
  {w:'crucial',pos:'a',m:'중요한',ex:'This step is crucial.'},
  {w:'cruel',pos:'a',m:'잔인한',ex:'It is cruel to hurt animals.'},
  {w:'cultivate',pos:'v',m:'경작하다',ex:'Farmers cultivate the land.'},
  {w:'curious',pos:'a',m:'호기심 많은',ex:'Children are naturally curious.'},
  {w:'deceive',pos:'v',m:'속이다',ex:'He tried to deceive his friends.'},
  {w:'declare',pos:'v',m:'선언하다',ex:'They will declare the winner.'},
  {w:'decrease',pos:'v',m:'감소하다',ex:'Prices will decrease next month.'},
  {w:'defend',pos:'v',m:'방어하다',ex:'Soldiers defend the country.'},
  {w:'define',pos:'v',m:'정의하다',ex:'Please define this word.'},
  {w:'delay',pos:'v',m:'지연시키다',ex:'Bad weather can delay the flight.'},
  {w:'deliberate',pos:'a',m:'고의적인',ex:'It was a deliberate lie.'},
  {w:'delight',pos:'n',m:'기쁨',ex:'The gift gave her great delight.'},
  {w:'deliver',pos:'v',m:'배달하다',ex:'They deliver mail every day.'},
  {w:'depend',pos:'v',m:'의존하다',ex:'Children depend on their parents.'},
  {w:'depress',pos:'v',m:'우울하게 하다',ex:'Rainy days depress him.'},
  {w:'deserve',pos:'v',m:'~할 자격이 있다',ex:'You deserve a reward.'},
  {w:'desire',pos:'n',m:'욕망',ex:'She has a strong desire to win.'},
  {w:'despair',pos:'n',m:'절망',ex:'He was filled with despair.'},
  {w:'desperate',pos:'a',m:'필사적인',ex:'They made a desperate attempt.'},
  {w:'destroy',pos:'v',m:'파괴하다',ex:'The fire could destroy the forest.'},
  {w:'detect',pos:'v',m:'탐지하다',ex:'The device can detect smoke.'},
  {w:'determine',pos:'v',m:'결정하다',ex:'We must determine the cause.'},
  {w:'devote',pos:'v',m:'헌신하다',ex:'She will devote her life to teaching.'},
  {w:'differ',pos:'v',m:'다르다',ex:'Opinions often differ.'},
  {w:'diminish',pos:'v',m:'줄어들다',ex:'The pain will diminish soon.'},
  {w:'disappoint',pos:'v',m:'실망시키다',ex:'The result may disappoint fans.'},
  {w:'discourage',pos:'v',m:'낙담시키다',ex:'Failure should not discourage you.'},
  {w:'disguise',pos:'v',m:'변장하다',ex:'He tried to disguise his voice.'},
  {w:'dismiss',pos:'v',m:'일축하다',ex:'Do not dismiss her idea.'},
  {w:'display',pos:'v',m:'전시하다',ex:'The museum will display the art.'},
  {w:'dispose',pos:'v',m:'처리하다',ex:'Please dispose of the trash.'},
  {w:'distant',pos:'a',m:'먼',ex:'They live in a distant town.'},
  {w:'distract',pos:'v',m:'산만하게 하다',ex:'Noise can distract students.'},
  {w:'distribute',pos:'v',m:'분배하다',ex:'They distribute food to the poor.'},
  {w:'disturb',pos:'v',m:'방해하다',ex:'Please do not disturb the baby.'},
  {w:'diverse',pos:'a',m:'다양한',ex:'The city has a diverse population.'},
  {w:'divide',pos:'v',m:'나누다',ex:'Please divide the cake into eight pieces.'},
  {w:'dominate',pos:'v',m:'지배하다',ex:'One team began to dominate the game.'},
  {w:'donate',pos:'v',m:'기부하다',ex:'They donate money to charity.'},
  {w:'doubt',pos:'n',m:'의심',ex:'I have no doubt about it.'},
  {w:'drift',pos:'v',m:'표류하다',ex:'The boat began to drift.'},
  {w:'dwell',pos:'v',m:'거주하다',ex:'They dwell in a small village.'},
  {w:'eager',pos:'a',m:'열망하는',ex:'She is eager to learn.'},
  {w:'earn',pos:'v',m:'벌다',ex:'He works hard to earn money.'},
  {w:'economy',pos:'n',m:'경제',ex:'The economy is growing.'},
  {w:'edge',pos:'n',m:'가장자리',ex:'He stood at the edge of the cliff.'},
  {w:'educate',pos:'v',m:'교육하다',ex:'Schools educate young minds.'},
  {w:'elaborate',pos:'a',m:'정교한',ex:'She made an elaborate plan.'},
  {w:'elegant',pos:'a',m:'우아한',ex:'She wore an elegant dress.'},
  {w:'embarrass',pos:'v',m:'당황하게 하다',ex:'The mistake will embarrass him.'},
  {w:'embrace',pos:'v',m:'받아들이다',ex:'They embrace new ideas.'},
  {w:'emerge',pos:'v',m:'나타나다',ex:'The sun will emerge from the clouds.'},
  {w:'emotion',pos:'n',m:'감정',ex:'Fear is a strong emotion.'},
  {w:'employ',pos:'v',m:'고용하다',ex:'The factory will employ more workers.'},
  {w:'enable',pos:'v',m:'가능하게 하다',ex:'The tool will enable faster work.'},
  {w:'endure',pos:'v',m:'견디다',ex:'They had to endure the cold.'},
  {w:'enormous',pos:'a',m:'거대한',ex:'The whale is an enormous animal.'},
  {w:'entertain',pos:'v',m:'즐겁게 하다',ex:'Clowns entertain children.'},
  {w:'environment',pos:'n',m:'환경',ex:'We must protect the environment.'},
  {w:'envy',pos:'n',m:'부러움',ex:'She felt envy toward her sister.'},
  {w:'equip',pos:'v',m:'갖추다',ex:'They will equip the team with tools.'},
  {w:'establish',pos:'v',m:'설립하다',ex:'They will establish a new company.'},
  {w:'evaluate',pos:'v',m:'평가하다',ex:'Teachers evaluate the essays.'},
  {w:'evolve',pos:'v',m:'진화하다',ex:'Animals evolve over time.'},
  {w:'exceed',pos:'v',m:'초과하다',ex:'The cost may exceed the budget.'},
  {w:'exclude',pos:'v',m:'제외하다',ex:'Do not exclude anyone from the team.'},
  {w:'exhibit',pos:'v',m:'전시하다',ex:'The gallery will exhibit new works.'},
  {w:'exist',pos:'v',m:'존재하다',ex:'Dinosaurs no longer exist.'},
  {w:'expense',pos:'n',m:'비용',ex:'Travel is a big expense.'},
  {w:'explore',pos:'v',m:'탐험하다',ex:'They want to explore the cave.'},
  {w:'expose',pos:'v',m:'노출시키다',ex:'Do not expose the film to light.'},
  {w:'extend',pos:'v',m:'연장하다',ex:'They will extend the deadline.'},
  {w:'external',pos:'a',m:'외부의',ex:'The building has external lights.'},
  {w:'extinct',pos:'a',m:'멸종된',ex:'The dodo is extinct.'},
  {w:'extraordinary',pos:'a',m:'비범한',ex:'She has extraordinary talent.'},
  {w:'fade',pos:'v',m:'바래다',ex:'The colors will fade in the sun.'},
  {w:'faint',pos:'a',m:'희미한',ex:'There was a faint sound.'},
  {w:'fascinate',pos:'v',m:'매혹하다',ex:'Space can fascinate children.'},
  {w:'fatigue',pos:'n',m:'피로',ex:'He felt great fatigue after work.'},
  {w:'fault',pos:'n',m:'잘못',ex:'It was not your fault.'},
  {w:'favor',pos:'n',m:'호의',ex:'Can you do me a favor?'},
  {w:'fee',pos:'n',m:'요금',ex:'The entrance fee is small.'},
  {w:'fierce',pos:'a',m:'사나운',ex:'The tiger gave a fierce roar.'},
  {w:'flee',pos:'v',m:'도망치다',ex:'The people had to flee the city.'},
  {w:'flexible',pos:'a',m:'유연한',ex:'Our schedule is flexible.'},
  {w:'float',pos:'v',m:'뜨다',ex:'Wood can float on water.'},
  {w:'flourish',pos:'v',m:'번성하다',ex:'The business began to flourish.'},
  {w:'forecast',pos:'n',m:'예보',ex:'The forecast promised rain.'},
  {w:'former',pos:'a',m:'이전의',ex:'The former teacher was kind.'},
  {w:'foundation',pos:'n',m:'기초',ex:'A house needs a strong foundation.'},
  {w:'frequent',pos:'a',m:'잦은',ex:'He is a frequent visitor.'},
  {w:'frighten',pos:'v',m:'겁먹게 하다',ex:'Loud noises frighten the dog.'},
  {w:'frustrate',pos:'v',m:'좌절시키다',ex:'The delay will frustrate travelers.'},
  {w:'fulfill',pos:'v',m:'성취하다',ex:'She hopes to fulfill her dream.'},
  {w:'function',pos:'n',m:'기능',ex:'Each button has a function.'},
  {w:'fund',pos:'n',m:'자금',ex:'They raised a fund for the school.'},
  {w:'furthermore',pos:'ad',m:'게다가',ex:'It is cheap; furthermore, it is safe.'},
  {w:'gain',pos:'v',m:'얻다',ex:'You can gain skills by practice.'},
  {w:'gather',pos:'v',m:'모으다',ex:'They gather every Sunday.'},
  {w:'gaze',pos:'v',m:'응시하다',ex:'She likes to gaze at the stars.'},
  {w:'generous',pos:'a',m:'관대한',ex:'He is generous with his time.'},
  {w:'gesture',pos:'n',m:'몸짓',ex:'She made a friendly gesture.'},
  {w:'glance',pos:'v',m:'흘긋 보다',ex:'He gave a quick glance.'},
  {w:'glory',pos:'n',m:'영광',ex:'The team won great glory.'},
  {w:'glow',pos:'v',m:'빛나다',ex:'The candles glow in the dark.'},
  {w:'govern',pos:'v',m:'통치하다',ex:'Leaders govern the country.'},
  {w:'grab',pos:'v',m:'붙잡다',ex:'He tried to grab the rope.'},
  {w:'grateful',pos:'a',m:'감사하는',ex:'I am grateful for your help.'},
  {w:'greed',pos:'n',m:'탐욕',ex:'Greed can destroy people.'},
  {w:'grief',pos:'n',m:'슬픔',ex:'She was full of grief.'},
  {w:'guarantee',pos:'v',m:'보장하다',ex:'We guarantee fast delivery.'},
  {w:'guilty',pos:'a',m:'죄책감의',ex:'He felt guilty about the lie.'},
  {w:'handle',pos:'v',m:'다루다',ex:'She can handle difficult tasks.'},
  {w:'harsh',pos:'a',m:'가혹한',ex:'The winter was harsh.'},
  {w:'harvest',pos:'n',m:'수확',ex:'The harvest was good this year.'},
  {w:'heal',pos:'v',m:'치유하다',ex:'Time can heal wounds.'},
  {w:'heritage',pos:'n',m:'유산',ex:'We must protect our heritage.'},
  {w:'hollow',pos:'a',m:'속이 빈',ex:'The tree is hollow inside.'},
  {w:'honor',pos:'n',m:'명예',ex:'It is an honor to meet you.'},
  {w:'horror',pos:'n',m:'공포',ex:'The movie was full of horror.'},
  {w:'hostile',pos:'a',m:'적대적인',ex:'The crowd became hostile.'},
  {w:'identify',pos:'v',m:'확인하다',ex:'Can you identify the man?'},
  {w:'illustrate',pos:'v',m:'설명하다',ex:'This example will illustrate the point.'},
  {w:'imply',pos:'v',m:'암시하다',ex:'His words imply a threat.'},
  {w:'impose',pos:'v',m:'부과하다',ex:'They will impose a fine.'},
  {w:'impress',pos:'v',m:'감명을 주다',ex:'Her speech will impress the judges.'},
  {w:'improve',pos:'v',m:'향상시키다',ex:'Practice will improve your skills.'},
  {w:'include',pos:'v',m:'포함하다',ex:'Meals include a free drink.'},
  {w:'income',pos:'n',m:'수입',ex:'Their income is low.'},
  {w:'increase',pos:'v',m:'증가하다',ex:'Prices continue to increase.'},
  {w:'independent',pos:'a',m:'독립적인',ex:'She is an independent thinker.'},
  {w:'infer',pos:'v',m:'추론하다',ex:'We can infer the meaning.'},
  {w:'influence',pos:'n',m:'영향',ex:'Parents have great influence.'},
  {w:'inform',pos:'v',m:'알리다',ex:'Please inform me of the change.'},
  {w:'inhabit',pos:'v',m:'서식하다',ex:'Many birds inhabit the forest.'},
  {w:'inherit',pos:'v',m:'물려받다',ex:'She will inherit the house.'},
  {w:'injure',pos:'v',m:'부상을 입히다',ex:'The fall could injure him.'},
  {w:'innocent',pos:'a',m:'무죄의',ex:'The court found him innocent.'},
  {w:'inquire',pos:'v',m:'문의하다',ex:'She will inquire about the job.'},
  {w:'inspire',pos:'v',m:'영감을 주다',ex:'Great teachers inspire students.'},
  {w:'install',pos:'v',m:'설치하다',ex:'They will install a new app.'},
  {w:'instant',pos:'a',m:'즉각적인',ex:'He gave an instant reply.'},
  {w:'instinct',pos:'n',m:'본능',ex:'Animals rely on instinct.'},
  {w:'instruct',pos:'v',m:'지시하다',ex:'The coach will instruct the players.'},
  {w:'insult',pos:'v',m:'모욕하다',ex:'Do not insult your friends.'},
  {w:'intend',pos:'v',m:'의도하다',ex:'I intend to study tonight.'},
  {w:'intense',pos:'a',m:'강렬한',ex:'The heat was intense.'},
  {w:'interact',pos:'v',m:'상호작용하다',ex:'Students interact in groups.'},
  {w:'interfere',pos:'v',m:'간섭하다',ex:'Do not interfere with their work.'},
  {w:'interrupt',pos:'v',m:'방해하다',ex:'Please do not interrupt me.'},
  {w:'invade',pos:'v',m:'침략하다',ex:'Enemies tried to invade the town.'},
  {w:'invent',pos:'v',m:'발명하다',ex:'He wants to invent a new machine.'},
  {w:'invest',pos:'v',m:'투자하다',ex:'They invest in new technology.'},
  {w:'investigate',pos:'v',m:'조사하다',ex:'Police will investigate the case.'},
  {w:'involve',pos:'v',m:'관련시키다',ex:'The job will involve travel.'},
  {w:'journey',pos:'n',m:'여행',ex:'The journey took three days.'},
  {w:'justice',pos:'n',m:'정의',ex:'People demand justice.'},
  {w:'justify',pos:'v',m:'정당화하다',ex:'Nothing can justify violence.'},
  {w:'keen',pos:'a',m:'열망하는',ex:'She is keen to learn.'},
  {w:'labor',pos:'n',m:'노동',ex:'The work required hard labor.'},
  {w:'lack',pos:'n',m:'부족',ex:'They suffer from a lack of water.'},
  {w:'launch',pos:'v',m:'시작하다',ex:'They will launch the rocket.'},
  {w:'lean',pos:'v',m:'기대다',ex:'Do not lean on the door.'},
  {w:'leap',pos:'v',m:'뛰어오르다',ex:'The cat will leap over the fence.'},
  {w:'liberty',pos:'n',m:'자유',ex:'People fought for liberty.'},
  {w:'literature',pos:'n',m:'문학',ex:'She studies English literature.'},
  {w:'locate',pos:'v',m:'위치를 찾다',ex:'Can you locate the file?'},
  {w:'loyal',pos:'a',m:'충성스러운',ex:'A dog is a loyal pet.'},
  {w:'magnificent',pos:'a',m:'웅장한',ex:'The view was magnificent.'},
  {w:'majority',pos:'n',m:'대다수',ex:'The majority agreed.'},
  {w:'manufacture',pos:'v',m:'제조하다',ex:'The factory will manufacture cars.'},
  {w:'massive',pos:'a',m:'거대한',ex:'A massive rock blocked the road.'},
  {w:'mature',pos:'a',m:'성숙한',ex:'He is mature for his age.'},
  {w:'means',pos:'n',m:'수단',ex:'Money is a means to an end.'},
  {w:'measure',pos:'v',m:'측정하다',ex:'Please measure the length.'},
  {w:'mention',pos:'v',m:'언급하다',ex:'He did not mention the problem.'},
  {w:'mercy',pos:'n',m:'자비',ex:'The king showed mercy.'},
  {w:'mere',pos:'a',m:'~에 불과한',ex:'It was a mere accident.'},
  {w:'migrate',pos:'v',m:'이주하다',ex:'Birds migrate in winter.'},
  {w:'mimic',pos:'v',m:'흉내내다',ex:'Parrots can mimic human speech.'},
  {w:'mission',pos:'n',m:'임무',ex:'Their mission was to save the ship.'},
  {w:'mixture',pos:'n',m:'혼합물',ex:'Air is a mixture of gases.'},
  {w:'modify',pos:'v',m:'수정하다',ex:'They will modify the design.'},
  {w:'monitor',pos:'v',m:'감시하다',ex:'Doctors monitor the patient.'},
  {w:'mood',pos:'n',m:'기분',ex:'She is in a good mood.'},
  {w:'motivate',pos:'v',m:'동기를 부여하다',ex:'Rewards can motivate students.'},
  {w:'multiply',pos:'v',m:'곱하다',ex:'Rabbits multiply quickly.'},
  {w:'mutual',pos:'a',m:'상호의',ex:'They share a mutual respect.'},
  {w:'naive',pos:'a',m:'순진한',ex:'He was naive to trust them.'},
  {w:'narrow',pos:'a',m:'좁은',ex:'The path is very narrow.'},
  {w:'neat',pos:'a',m:'깔끔한',ex:'Her desk is always neat.'},
  {w:'neglect',pos:'v',m:'방치하다',ex:'Do not neglect your health.'},
  {w:'nevertheless',pos:'ad',m:'그럼에도',ex:'It was hard; nevertheless, she tried.'},
  {w:'noble',pos:'a',m:'고귀한',ex:'He had a noble heart.'},
  {w:'notice',pos:'v',m:'알아차리다',ex:'Did you notice the change?'},
  {w:'notion',pos:'n',m:'개념',ex:'She had no notion of the danger.'},
  {w:'nourish',pos:'v',m:'영양을 주다',ex:'Good food will nourish the body.'},
  {w:'objective',pos:'n',m:'목표',ex:'Our objective is clear.'},
  {w:'observe',pos:'v',m:'관찰하다',ex:'Scientists observe the stars.'},
  {w:'obstacle',pos:'n',m:'장애물',ex:'Fear is a big obstacle.'},
  {w:'obtain',pos:'v',m:'얻다',ex:'You must obtain a ticket.'},
  {w:'occur',pos:'v',m:'발생하다',ex:'The accident could occur again.'},
  {w:'offend',pos:'v',m:'기분 상하게 하다',ex:'His joke may offend some people.'},
  {w:'operate',pos:'v',m:'작동하다',ex:'The machine will operate quietly.'},
  {w:'oppose',pos:'v',m:'반대하다',ex:'Many people oppose the plan.'},
  {w:'optimistic',pos:'a',m:'낙관적인',ex:'She stayed optimistic.'},
  {w:'ordinary',pos:'a',m:'평범한',ex:'It was an ordinary day.'},
  {w:'organize',pos:'v',m:'조직하다',ex:'They will organize an event.'},
  {w:'origin',pos:'n',m:'기원',ex:'The word has a Latin origin.'},
  {w:'outcome',pos:'n',m:'결과',ex:'The outcome was a surprise.'},
  {w:'outstanding',pos:'a',m:'뛰어난',ex:'She gave an outstanding performance.'},
  {w:'panic',pos:'v',m:'당황하다',ex:'Do not panic in an emergency.'},
  {w:'passion',pos:'n',m:'열정',ex:'Music is her passion.'},
  {w:'patient',pos:'a',m:'참을성 있는',ex:'You must be patient.'},
  {w:'peculiar',pos:'a',m:'이상한',ex:'There was a peculiar smell.'},
  {w:'perceive',pos:'v',m:'인식하다',ex:'We perceive colors with our eyes.'},
  {w:'perform',pos:'v',m:'공연하다',ex:'The band will perform tonight.'},
  {w:'permanent',pos:'a',m:'영구적인',ex:'This is a permanent solution.'},
  {w:'permit',pos:'v',m:'허가하다',ex:'The rules do not permit smoking.'},
  {w:'perspective',pos:'n',m:'관점',ex:'Try a different perspective.'},
  {w:'phenomenon',pos:'n',m:'현상',ex:'Rainbows are a natural phenomenon.'},
  {w:'portion',pos:'n',m:'부분',ex:'He ate a large portion.'},
  {w:'portray',pos:'v',m:'묘사하다',ex:'The book will portray a hero.'},
  {w:'possess',pos:'v',m:'소유하다',ex:'They possess great wealth.'},
  {w:'poverty',pos:'n',m:'가난',ex:'Many families live in poverty.'},
  {w:'praise',pos:'v',m:'칭찬하다',ex:'Teachers praise good work.'},
  {w:'precious',pos:'a',m:'소중한',ex:'Water is precious in the desert.'},
  {w:'predict',pos:'v',m:'예측하다',ex:'No one can predict the future.'},
  {w:'prefer',pos:'v',m:'선호하다',ex:'I prefer tea to coffee.'},
  {w:'prejudice',pos:'n',m:'편견',ex:'We should fight prejudice.'},
  {w:'preserve',pos:'v',m:'보존하다',ex:'We must preserve nature.'},
  {w:'previous',pos:'a',m:'이전의',ex:'See the previous chapter.'},
  {w:'primary',pos:'a',m:'주요한',ex:'Safety is our primary concern.'},
  {w:'principle',pos:'n',m:'원칙',ex:'Honesty is a good principle.'},
  {w:'prior',pos:'a',m:'이전의',ex:'He had no prior experience.'},
  {w:'privilege',pos:'n',m:'특권',ex:'Education is a privilege.'},
  {w:'proceed',pos:'v',m:'진행하다',ex:'Please proceed to the gate.'},
  {w:'profound',pos:'a',m:'심오한',ex:'The book had a profound message.'},
  {w:'prohibit',pos:'v',m:'금지하다',ex:'The law will prohibit smoking.'},
  {w:'prominent',pos:'a',m:'저명한',ex:'She is a prominent scientist.'},
  {w:'promote',pos:'v',m:'촉진하다',ex:'Exercise will promote health.'},
  {w:'prompt',pos:'a',m:'신속한',ex:'He gave a prompt reply.'},
  {w:'proper',pos:'a',m:'적절한',ex:'Use the proper tool.'},
  {w:'propose',pos:'v',m:'제안하다',ex:'They will propose a new plan.'},
  {w:'prosper',pos:'v',m:'번영하다',ex:'The town began to prosper.'},
  {w:'protect',pos:'v',m:'보호하다',ex:'Helmets protect your head.'},
  {w:'protest',pos:'v',m:'항의하다',ex:'Students protest the decision.'},
  {w:'prove',pos:'v',m:'증명하다',ex:'He will prove his point.'},
  {w:'provide',pos:'v',m:'제공하다',ex:'Schools provide free books.'},
  {w:'publish',pos:'v',m:'출판하다',ex:'She will publish her novel.'},
  {w:'punish',pos:'v',m:'처벌하다',ex:'The rules punish cheating.'},
  {w:'purchase',pos:'v',m:'구매하다',ex:'They will purchase a house.'},
  {w:'pure',pos:'a',m:'순수한',ex:'The water is pure.'},
  {w:'pursue',pos:'v',m:'추구하다',ex:'She will pursue her dream.'},
  {w:'qualify',pos:'v',m:'자격을 얻다',ex:'She will qualify for the finals.'},
  {w:'quantity',pos:'n',m:'양',ex:'We need a small quantity.'},
  {w:'quit',pos:'v',m:'그만두다',ex:'He wants to quit smoking.'},
  {w:'rapid',pos:'a',m:'빠른',ex:'There was a rapid change.'},
  {w:'rare',pos:'a',m:'드문',ex:'This bird is very rare.'},
  {w:'react',pos:'v',m:'반응하다',ex:'How did they react to the news?'},
  {w:'realize',pos:'v',m:'깨닫다',ex:'He will realize his mistake.'},
  {w:'rebel',pos:'v',m:'반항하다',ex:'Teenagers sometimes rebel.'},
  {w:'recall',pos:'v',m:'기억해내다',ex:'I cannot recall his name.'},
  {w:'recognize',pos:'v',m:'인식하다',ex:'I did not recognize you.'},
  {w:'recommend',pos:'v',m:'추천하다',ex:'I recommend this book.'},
  {w:'reduce',pos:'v',m:'줄이다',ex:'We must reduce waste.'},
  {w:'refer',pos:'v',m:'언급하다',ex:'Please refer to the map.'},
  {w:'reflect',pos:'v',m:'반영하다',ex:'Mirrors reflect light.'},
  {w:'reform',pos:'n',m:'개혁',ex:'They demand reform.'},
  {w:'refuse',pos:'v',m:'거절하다',ex:'He will refuse the offer.'},
  {w:'regard',pos:'v',m:'여기다',ex:'They regard him as a hero.'},
  {w:'register',pos:'v',m:'등록하다',ex:'Please register for the class.'},
  {w:'regret',pos:'v',m:'후회하다',ex:'You will regret it later.'},
  {w:'regulate',pos:'v',m:'규제하다',ex:'Laws regulate business.'},
  {w:'reinforce',pos:'v',m:'강화하다',ex:'Practice will reinforce learning.'},
  {w:'relate',pos:'v',m:'관련시키다',ex:'These facts relate to the case.'},
  {w:'relative',pos:'n',m:'친척',ex:'My relative lives abroad.'},
  {w:'release',pos:'v',m:'발표하다',ex:'They will release the film.'},
  {w:'relevant',pos:'a',m:'관련 있는',ex:'Give me relevant facts.'},
  {w:'relief',pos:'n',m:'안도',ex:'She felt great relief.'},
  {w:'rely',pos:'v',m:'의존하다',ex:'You can rely on me.'},
  {w:'remark',pos:'n',m:'발언',ex:'He made a rude remark.'},
  {w:'remind',pos:'v',m:'상기시키다',ex:'Please remind me later.'},
  {w:'repair',pos:'v',m:'수리하다',ex:'He will repair the car.'},
  {w:'replace',pos:'v',m:'대체하다',ex:'We must replace the battery.'},
  {w:'represent',pos:'v',m:'대표하다',ex:'She will represent the school.'},
  {w:'reputation',pos:'n',m:'명성',ex:'The hotel has a good reputation.'},
  {w:'require',pos:'v',m:'요구하다',ex:'These jobs require skill.'},
  {w:'rescue',pos:'v',m:'구조하다',ex:'They will rescue the climbers.'},
  {w:'resemble',pos:'v',m:'닮다',ex:'You resemble your mother.'},
  {w:'reserve',pos:'v',m:'예약하다',ex:'I want to reserve a table.'},
  {w:'resist',pos:'v',m:'저항하다',ex:'He could not resist the cake.'},
  {w:'resolve',pos:'v',m:'해결하다',ex:'They will resolve the dispute.'},
  {w:'resource',pos:'n',m:'자원',ex:'Water is a vital resource.'},
  {w:'respond',pos:'v',m:'응답하다',ex:'Please respond soon.'},
  {w:'responsible',pos:'a',m:'책임이 있는',ex:'You are responsible for this.'},
  {w:'restore',pos:'v',m:'복원하다',ex:'They will restore the old castle.'},
  {w:'restrict',pos:'v',m:'제한하다',ex:'Rules restrict our freedom.'},
  {w:'retain',pos:'v',m:'유지하다',ex:'Plants retain water.'},
  {w:'retire',pos:'v',m:'은퇴하다',ex:'He will retire next year.'},
  {w:'revenge',pos:'n',m:'복수',ex:'He wanted revenge.'},
  {w:'reverse',pos:'v',m:'뒤집다',ex:'You cannot reverse the past.'},
  {w:'revise',pos:'v',m:'수정하다',ex:'Please revise your essay.'},
  {w:'reward',pos:'n',m:'보상',ex:'Hard work brings reward.'},
  {w:'ridiculous',pos:'a',m:'우스꽝스러운',ex:'The idea sounds ridiculous.'},
  {w:'rigid',pos:'a',m:'뻣뻣한',ex:'The rules are too rigid.'},
  {w:'roar',pos:'v',m:'으르렁거리다',ex:'The lions roar at night.'},
  {w:'rough',pos:'a',m:'거친',ex:'The road was rough.'},
  {w:'routine',pos:'n',m:'일상',ex:'Exercise is part of his routine.'},
  {w:'rural',pos:'a',m:'시골의',ex:'They live in a rural area.'},
  {w:'satisfy',pos:'v',m:'만족시키다',ex:'The meal will satisfy your hunger.'},
  {w:'scarce',pos:'a',m:'부족한',ex:'Water is scarce here.'},
  {w:'scatter',pos:'v',m:'흩뿌리다',ex:'The wind will scatter the seeds.'},
  {w:'scent',pos:'n',m:'향기',ex:'The flower has a sweet scent.'},
  {w:'scold',pos:'v',m:'꾸짖다',ex:'The teacher will scold him.'},
  {w:'scream',pos:'v',m:'비명 지르다',ex:'She began to scream in fear.'},
  {w:'seek',pos:'v',m:'찾다',ex:'They seek a better life.'},
  {w:'seize',pos:'v',m:'붙잡다',ex:'He tried to seize the chance.'},
  {w:'select',pos:'v',m:'선택하다',ex:'Please select an answer.'},
  {w:'sensible',pos:'a',m:'분별 있는',ex:'That is a sensible choice.'},
  {w:'sensitive',pos:'a',m:'민감한',ex:'She is sensitive to noise.'},
  {w:'separate',pos:'v',m:'분리하다',ex:'Please separate the good from the bad.'},
  {w:'settle',pos:'v',m:'정착하다',ex:'They will settle in the city.'},
  {w:'severe',pos:'a',m:'심각한',ex:'He has a severe cold.'},
  {w:'shallow',pos:'a',m:'얕은',ex:'The pool is shallow.'},
  {w:'shame',pos:'n',m:'부끄러움',ex:'He felt shame after lying.'},
  {w:'shelter',pos:'n',m:'피난처',ex:'They found shelter from the rain.'},
  {w:'shift',pos:'v',m:'옮기다',ex:'Please shift the box.'},
  {w:'shrink',pos:'v',m:'줄어들다',ex:'The shirt will shrink in hot water.'},
  {w:'sigh',pos:'v',m:'한숨 쉬다',ex:'She began to sigh.'},
  {w:'silly',pos:'a',m:'어리석은',ex:'That was a silly mistake.'},
  {w:'sincere',pos:'a',m:'진실한',ex:'He gave a sincere apology.'},
  {w:'situation',pos:'n',m:'상황',ex:'The situation is serious.'},
  {w:'solve',pos:'v',m:'해결하다',ex:'Let us solve the problem.'},
  {w:'source',pos:'n',m:'원천',ex:'The sun is a source of energy.'},
  {w:'spare',pos:'a',m:'여분의',ex:'Do you have a spare pen?'},
  {w:'species',pos:'n',m:'종',ex:'This species is rare.'},
  {w:'specific',pos:'a',m:'구체적인',ex:'Give a specific example.'},
  {w:'spill',pos:'v',m:'쏟다',ex:'Be careful not to spill the milk.'},
  {w:'split',pos:'v',m:'나누다',ex:'They will split the bill.'},
  {w:'spoil',pos:'v',m:'망치다',ex:'Rain will spoil the picnic.'},
  {w:'spread',pos:'v',m:'퍼지다',ex:'The fire will spread quickly.'},
  {w:'stable',pos:'a',m:'안정적인',ex:'The economy is stable.'},
  {w:'stare',pos:'v',m:'응시하다',ex:'Do not stare at people.'},
  {w:'startle',pos:'v',m:'깜짝 놀라게 하다',ex:'The noise will startle the birds.'},
  {w:'starve',pos:'v',m:'굶주리다',ex:'Many people starve in war.'},
  {w:'steady',pos:'a',m:'꾸준한',ex:'He made steady progress.'},
  {w:'stern',pos:'a',m:'엄격한',ex:'The judge was stern.'},
  {w:'stimulate',pos:'v',m:'자극하다',ex:'Coffee can stimulate the brain.'},
  {w:'strategy',pos:'n',m:'전략',ex:'We need a new strategy.'},
  {w:'strengthen',pos:'v',m:'강화하다',ex:'Exercise will strengthen muscles.'},
  {w:'stretch',pos:'v',m:'늘이다',ex:'Please stretch your arms.'},
  {w:'strict',pos:'a',m:'엄격한',ex:'The teacher is strict.'},
  {w:'strive',pos:'v',m:'노력하다',ex:'We strive for success.'},
  {w:'struggle',pos:'v',m:'분투하다',ex:'They struggle to survive.'},
  {w:'stubborn',pos:'a',m:'고집 센',ex:'He is very stubborn.'},
  {w:'submit',pos:'v',m:'제출하다',ex:'Please submit your report.'},
  {w:'substance',pos:'n',m:'물질',ex:'Water is a clear substance.'},
  {w:'substitute',pos:'v',m:'대체하다',ex:'You can substitute honey for sugar.'},
  {w:'subtle',pos:'a',m:'미묘한',ex:'There was a subtle difference.'},
  {w:'succeed',pos:'v',m:'성공하다',ex:'She will succeed in life.'},
  {w:'sufficient',pos:'a',m:'충분한',ex:'We have sufficient food.'},
  {w:'suggest',pos:'v',m:'제안하다',ex:'I suggest a short break.'},
  {w:'suitable',pos:'a',m:'적합한',ex:'This film is suitable for kids.'},
  {w:'summit',pos:'n',m:'정상',ex:'They reached the summit.'},
  {w:'superior',pos:'a',m:'우수한',ex:'This model is superior.'},
  {w:'suppose',pos:'v',m:'가정하다',ex:'Suppose you win the prize.'},
  {w:'suppress',pos:'v',m:'억누르다',ex:'He tried to suppress a laugh.'},
  {w:'surface',pos:'n',m:'표면',ex:'The surface is smooth.'},
  {w:'surround',pos:'v',m:'둘러싸다',ex:'Trees surround the house.'},
  {w:'survive',pos:'v',m:'생존하다',ex:'They will survive the storm.'},
  {w:'suspect',pos:'v',m:'의심하다',ex:'Police suspect the man.'},
  {w:'suspend',pos:'v',m:'정지시키다',ex:'They will suspend the game.'},
  {w:'sustain',pos:'v',m:'지속하다',ex:'Food will sustain life.'},
  {w:'swear',pos:'v',m:'맹세하다',ex:'I swear to tell the truth.'},
  {w:'sympathy',pos:'n',m:'동정',ex:'She felt sympathy for them.'},
  {w:'tackle',pos:'v',m:'다루다',ex:'We must tackle the problem.'},
  {w:'talent',pos:'n',m:'재능',ex:'She has a talent for music.'},
  {w:'tame',pos:'v',m:'길들이다',ex:'He tried to tame the horse.'},
  {w:'tease',pos:'v',m:'놀리다',ex:'Do not tease your brother.'},
  {w:'tend',pos:'v',m:'~하는 경향이 있다',ex:'Prices tend to rise.'},
  {w:'tense',pos:'a',m:'긴장한',ex:'The room was tense.'},
  {w:'terror',pos:'n',m:'공포',ex:'The children screamed in terror.'},
  {w:'theme',pos:'n',m:'주제',ex:'Love is the theme of the song.'},
  {w:'thorough',pos:'a',m:'철저한',ex:'She made a thorough check.'},
  {w:'threaten',pos:'v',m:'위협하다',ex:'The storm will threaten the coast.'},
  {w:'thrive',pos:'v',m:'번성하다',ex:'Plants thrive in sunlight.'},
  {w:'tidy',pos:'a',m:'깔끔한',ex:'Keep your room tidy.'},
  {w:'tolerate',pos:'v',m:'참다',ex:'I cannot tolerate rudeness.'},
  {w:'trace',pos:'n',m:'흔적',ex:'There was no trace of him.'},
  {w:'tradition',pos:'n',m:'전통',ex:'This is an old tradition.'},
  {w:'tragedy',pos:'n',m:'비극',ex:'The play is a tragedy.'},
  {w:'transfer',pos:'v',m:'옮기다',ex:'They will transfer the money.'},
  {w:'transform',pos:'v',m:'변형시키다',ex:'Heat can transform ice into water.'},
  {w:'translate',pos:'v',m:'번역하다',ex:'Please translate this letter.'},
  {w:'transport',pos:'v',m:'운송하다',ex:'Trucks transport goods.'},
  {w:'treasure',pos:'n',m:'보물',ex:'They found hidden treasure.'},
  {w:'treat',pos:'v',m:'다루다',ex:'Doctors treat patients.'},
  {w:'tremble',pos:'v',m:'떨다',ex:'Her hands began to tremble.'},
  {w:'tremendous',pos:'a',m:'엄청난',ex:'It was a tremendous success.'},
  {w:'trend',pos:'n',m:'경향',ex:'Fashion follows a trend.'},
  {w:'trial',pos:'n',m:'시험',ex:'It was a difficult trial.'},
  {w:'triumph',pos:'n',m:'승리',ex:'The win was a great triumph.'},
  {w:'typical',pos:'a',m:'전형적인',ex:'It was a typical winter day.'},
  {w:'ultimate',pos:'a',m:'궁극적인',ex:'Our ultimate goal is peace.'},
  {w:'undergo',pos:'v',m:'겪다',ex:'She will undergo surgery.'},
  {w:'undertake',pos:'v',m:'착수하다',ex:'They will undertake a big project.'},
  {w:'unique',pos:'a',m:'독특한',ex:'Each person is unique.'},
  {w:'unite',pos:'v',m:'연합하다',ex:'The teams will unite.'},
  {w:'universal',pos:'a',m:'보편적인',ex:'Music is a universal language.'},
  {w:'urban',pos:'a',m:'도시의',ex:'Urban life is busy.'},
  {w:'urge',pos:'v',m:'촉구하다',ex:'They urge people to vote.'},
  {w:'urgent',pos:'a',m:'긴급한',ex:'This is an urgent matter.'},
  {w:'utilize',pos:'v',m:'활용하다',ex:'We should utilize the space.'},
  {w:'vague',pos:'a',m:'모호한',ex:'He gave a vague answer.'},
  {w:'vain',pos:'a',m:'헛된',ex:'Their efforts were in vain.'},
  {w:'valid',pos:'a',m:'유효한',ex:'The ticket is still valid.'},
  {w:'valuable',pos:'a',m:'귀중한',ex:'Time is valuable.'},
  {w:'vanish',pos:'v',m:'사라지다',ex:'The stars will vanish at dawn.'},
  {w:'variety',pos:'n',m:'다양성',ex:'The shop sells a variety of goods.'},
  {w:'various',pos:'a',m:'다양한',ex:'There are various reasons.'},
  {w:'vary',pos:'v',m:'다양하다',ex:'Prices vary by season.'},
  {w:'vast',pos:'a',m:'광대한',ex:'The desert is vast.'},
  {w:'venture',pos:'n',m:'모험',ex:'It was a risky venture.'},
  {w:'victim',pos:'n',m:'희생자',ex:'He was a victim of the crime.'},
  {w:'vivid',pos:'a',m:'생생한',ex:'She had a vivid dream.'},
  {w:'volunteer',pos:'v',m:'자원하다',ex:'She will volunteer at the shelter.'},
  {w:'vote',pos:'v',m:'투표하다',ex:'Citizens vote for a leader.'},
  {w:'wander',pos:'v',m:'헤매다',ex:'They like to wander in the forest.'},
  {w:'warn',pos:'v',m:'경고하다',ex:'The signs warn of danger.'},
  {w:'weaken',pos:'v',m:'약화시키다',ex:'Illness will weaken the body.'},
  {w:'wealth',pos:'n',m:'부',ex:'He gained great wealth.'},
  {w:'weep',pos:'v',m:'울다',ex:'She began to weep.'},
  {w:'weird',pos:'a',m:'이상한',ex:'That was a weird noise.'},
  {w:'welfare',pos:'n',m:'복지',ex:'They care about public welfare.'},
  {w:'widespread',pos:'a',m:'널리 퍼진',ex:'The disease was widespread.'},
  {w:'wisdom',pos:'n',m:'지혜',ex:'Age brings wisdom.'},
  {w:'withdraw',pos:'v',m:'철회하다',ex:'He will withdraw the money.'},
  {w:'worship',pos:'v',m:'숭배하다',ex:'They worship many gods.'},
  {w:'worth',pos:'a',m:'~의 가치가 있는',ex:'The trip is worth the cost.'},
  {w:'yield',pos:'v',m:'산출하다',ex:'The field will yield much rice.'},
  // ── 부사 보강(고빈도 수능·고1) — 품사 편중 완화 ──
  {w:'however',pos:'ad',m:'그러나',ex:'The plan is good; however, it costs a lot.'},
  {w:'therefore',pos:'ad',m:'그러므로',ex:'He was late; therefore, he missed the bus.'},
  {w:'moreover',pos:'ad',m:'게다가',ex:'The hotel is cheap; moreover, it is clean.'},
  {w:'gradually',pos:'ad',m:'점차',ex:'The weather gradually got warmer.'},
  {w:'eventually',pos:'ad',m:'결국',ex:'She eventually found her lost keys.'},
  {w:'frequently',pos:'ad',m:'자주',ex:'He frequently visits his grandmother.'},
  {w:'rarely',pos:'ad',m:'드물게',ex:'She rarely eats meat these days.'},
  {w:'seldom',pos:'ad',m:'좀처럼 않다',ex:'He seldom makes the same mistake twice.'},
  {w:'immediately',pos:'ad',m:'즉시',ex:'Call me immediately if there is a problem.'},
  {w:'constantly',pos:'ad',m:'끊임없이',ex:'The baby cries constantly at night.'},
  {w:'deliberately',pos:'ad',m:'고의로',ex:'He deliberately ignored my question.'},
  {w:'thoroughly',pos:'ad',m:'철저히',ex:'Please read the manual thoroughly.'},
  {w:'briefly',pos:'ad',m:'잠시; 간략히',ex:'She spoke briefly about her new plan.'},
  {w:'precisely',pos:'ad',m:'정확히',ex:'The train arrived precisely on time.'},
  {w:'entirely',pos:'ad',m:'전적으로',ex:'The mistake was entirely my fault.'},
  {w:'merely',pos:'ad',m:'단지',ex:'It was merely a harmless joke.'},
  {w:'hardly',pos:'ad',m:'거의 않다',ex:'I can hardly hear you from here.'},
  {w:'nearly',pos:'ad',m:'거의',ex:'We are nearly finished with the work.'},
  {w:'slightly',pos:'ad',m:'약간',ex:'The prices rose slightly this year.'},
  {w:'extremely',pos:'ad',m:'극도로',ex:'The final test was extremely difficult.'},
  {w:'particularly',pos:'ad',m:'특히',ex:'I particularly like this quiet song.'},
  {w:'occasionally',pos:'ad',m:'가끔',ex:'We occasionally go to the beach together.'},
  {w:'permanently',pos:'ad',m:'영구히',ex:'He moved permanently to another city.'},
  {w:'obviously',pos:'ad',m:'분명히',ex:'She was obviously upset about the news.'},
  {w:'apparently',pos:'ad',m:'보아하니',ex:'Apparently, the shop is closed today.'},
  {w:'certainly',pos:'ad',m:'틀림없이',ex:'I will certainly help you tomorrow.'},
  {w:'definitely',pos:'ad',m:'확실히',ex:'This is definitely the best choice.'},
  {w:'seriously',pos:'ad',m:'진지하게; 심각하게',ex:'You should take this warning seriously.'},
  {w:'gently',pos:'ad',m:'부드럽게',ex:'She gently closed the bedroom door.'},
  {w:'suddenly',pos:'ad',m:'갑자기',ex:'The lights suddenly went out.'},
  {w:'ultimately',pos:'ad',m:'궁극적으로',ex:'Ultimately, the final decision is yours.'},
  {w:'meanwhile',pos:'ad',m:'그동안',ex:'Meanwhile, I will prepare the dinner.'},
  {w:'otherwise',pos:'ad',m:'그렇지 않으면',ex:'Hurry up, otherwise we will be late.'},
  {w:'somewhat',pos:'ad',m:'다소',ex:'The long movie was somewhat boring.'},
  {w:'indeed',pos:'ad',m:'실로',ex:'It was indeed a great success.'},
  {w:'instead',pos:'ad',m:'대신에',ex:'Let us walk there instead.'},
  {w:'rather',pos:'ad',m:'오히려; 상당히',ex:'It is rather cold outside today.'},
  {w:'roughly',pos:'ad',m:'대략',ex:'The whole trip takes roughly two hours.'},
  {w:'widely',pos:'ad',m:'널리',ex:'The surprising news spread widely.'},
  {w:'highly',pos:'ad',m:'매우',ex:'She is a highly skilled doctor.'},
  {w:'mostly',pos:'ad',m:'대부분',ex:'The audience was mostly students.'},
  {w:'simply',pos:'ad',m:'그냥; 단순히',ex:'Simply follow the instructions on the box.'},
  {w:'deeply',pos:'ad',m:'깊이',ex:'He was deeply moved by the film.'},
  {w:'instantly',pos:'ad',m:'즉각',ex:'The new medicine worked instantly.'},
  {w:'namely',pos:'ad',m:'즉',ex:'One student was absent, namely Tom.'},
  {w:'likewise',pos:'ad',m:'마찬가지로',ex:'She works hard, and her sister does likewise.'},
];
